### ISSUE TITLE
Jobs submitted to openlava report having insufficient slots...

### ISSUE THREAD

**Issue by malachig** [genome/gms#10]
Alignment jobs immediately enter a 'pending' state.  bjobs -l reports the following:

PENDING REASONS:
Not enough job slot(s);
Not enough job slot(s);

The resource request looks like this:

```
4 Processors Requested, Requested Resources <select[ncpus>=4 && mem>=8192] span[hosts=1] rusage[mem=8192]>
```

It seems that if you do 'bmod -n 1', the number of 'Processors Requested' is reduced and the job seems to fire off.  Changing the 'Requested Resources' with 'bmod -R ...' does not seem to have an effect as long as 'Processors Requested' is greater than 1.  

I am testing on a VM that thinks it has 24 cpus.  Not sure if this problem is VM specific or just related to openlava...

**Comment by sakoht** [comment]
I just pushed a change to not use his with openlava. It seems redundant with select and rusage.  If it is not, restoring its functionality may improve efficient use of resources with openlava.

**Comment by malachig** [comment]
It seem that this has been working smoothly for a while now.  Ref-align and other jobs in the standalone GMS no longer hang in a Pending state now that the 'Processors Requested' value is not set when submitting resource requests to openlava.

I believe the reference to openlava specific code that Scott makes above is here:
Genome/InstrumentData/AlignmentResult/Bwa.pm

**Comment by gatoravi** [comment]
OK, i think the commit that Scott( or Obi?) made is this one, 
genome/tgi-workflow@dbd055c5ccb8f0c6ab04e57b794eeb114591f0f6

Looks like the `ncpus` option is still used but `-n` is disabled for OPENLAVA.
