### ISSUE TITLE
R package 'filehash' can no longer be installed in R-2.15.2 via install.packages()

### ISSUE THREAD

**Issue by malachig** [genome/gms#100]
Something has changed in the R package management system.  While this package 'filehash' is still available, will install successfully and seems to be working.  It is no longer official supported.  I will change the method of installation for this package to use a manual install procedure.  I chose the version of this package currently used in TGI (filehash_2.2-1). 

``` bash
wget http://cran.r-project.org/src/contrib/Archive/filehash/filehash_2.2-1.tar.gz
$R_BIN CMD INSTALL --library=$R_INSTALL_DIR/lib/R/library filehash_2.2-1.tar.gz
```

**Comment by malachig** [comment]
This is working and was added here:
https://github.com/genome/gms/commit/daf45087feb9663c65ea18a276d8d9fb90cfb1ea

I have also added a check for successful installation of all packages to the make target: done-host/custom-r
https://github.com/genome/gms/commit/0c713003b50d04a77557b163da1bcef89e68b43a

Hopefully this will help us avoid the case where the R installation has broken and we fail to notice during the installation.

**Comment by sakoht** [comment]
Awesome.

**Comment by malachig** [comment]
I am concerned that even if nothing changes on our end, the installation can regularly break because of the actions of the R development team.  They seem to routinely break package dependencies in older versions of R.  Furthermore, older versions of packages are not guaranteed to be available in the future.  There are versions of packages we are using in production at TGI that are now unavailable from the CRAN archives.  If we can build a debian package of every R dependency, this problem will go away.  In the mean time I have done the following:
- resolved every R dependency manually
- changed the installer to install all CRAN packages from archives instead of using install.packages()
- selected the exact version of each package used within TGI for every CRAN dependency
- created a static meta-package of all of these packages and stored in here:
  http://genome.wustl.edu/pub/software/gms/testdata/GMS1/setup/archive-files/r-cran-archives-2014-02-15.tar.gz

Relevant commits here:
https://github.com/genome/gms/commit/0ac6ad1a639e0351b7834d60335d358925809e2a
https://github.com/genome/gms/commit/8e76d5b8a2af6e6bb0bea36d706f325f8e479141
https://github.com/genome/gms/commit/d0b835f9b6006990f1da4bcc46be3d5c0df13b38
https://github.com/genome/gms/commit/dbb86a39c2b78d581266fdac60c8eef090068183

This approach has **not** been applied to the bioconductor packages.  It could be, but just like this task I just completed.  Would take a lot of searching for the correct version each package, testing install order, etc.

**Comment by sakoht** [comment]
If the R packages were part of the apt mirror used during installation this wouldn't be a concern.

**Comment by malachig** [comment]
Yes, I stated this in my last comment: "If we can build a debian package of every R dependency, this problem will go away."

They **are** part of the apt mirror right now.  Indeed we are installing R and our dependencies two ways.  One of those ways is from Debian packages.  This debian based install currently "succeeds" but results in a completely broken installation of R.  Many R libraries can not be loaded and many errors in the pipelines result.  

This is why we went down the road of creating a separate R installation in the first place.  And it works and has allowed us to move forward on other issues.  When R 3.0.X was released it fundamentally broken the way R debian packages were configured.  We can probably install a new version of R without trying to specify certain old versions of R libraries this way.  But we know that we need certain old version of certain R libraries.  When we try to specify these we wind up with a half-baked broken R installation.  If we don't use the old versions of R libraries we would have to substantially rewrite various tools that use ggplot, etc.

In theory it can be fixed by pegging certain R dependencies to certain package versions.  Efforts to resolve a working combination have been documented throughout github issues.  It has proved to be very, very difficult to get this to work cleanly.  @kindjal has dedicated significant time to working this mess out.  He continues to work towards a cleaner solution.  Of course none of this solves the problem that some R libraries we use simply are not available as debian packages though.

**Comment by malachig** [comment]
I switched to using the static tarball of R CRAN packages in these commits:
https://github.com/genome/gms/commit/08cafe6c94829b0283ba6a27609090dfb23653c1
https://github.com/genome/gms/commit/a2e53570d1b5d1f88855ea7da02684d8f911973c

Hopefully this improves stability of the install while we work towards a more robust solution involving Debian packages.  As I mentioned above, installation of BioConductor dependencies is still using their package manager:

```
bioc_package_list = c('affy', 'Biobase', 'cummeRbund', 'DNAcopy', 'edgeR', 'limma', 'gcrma', 'genefilter',
                      'geneplotter', 'GenomeGraphs', 'lumi', 'methylumi', 'multtest', 'preprocessCore', 'ChemmineR')

pkgTestBioc <- function(x){
  if (!require(x,character.only = TRUE)){
    biocLite(x,ask=FALSE,suppressUpdates=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}

source("http://bioconductor.org/biocLite.R")
for (bioc_package_name in bioc_package_list){
  pkgTestBioc(bioc_package_name);
}
```

This works fairly nicely but its unclear how fragile it will be over time.  I'll leave this issue open for a while longer in case we decide that we also want to make the bioconductor library installation more specific (i.e. use exactly the same versions used in TGI) and more static.

**Comment by sakoht** [comment]
Yeah probably wise.

I wish that cran2deb could be trusted more but it is kinda the Wild West.  With luck, over time, it will mature to a more rigorous level of stability.

**Comment by malachig** [comment]
Yes, it would be great if cran2deb was more thorough.  Same thing for Bioconductor which seems to be even more poorly supported in the form of Debian packages.  For now we are still thinking about building a static meta-package of all our Bioconductor dependencies.  Leaving this ticket open until that is resolved one way or the other.

**Comment by malachig** [comment]
The custom/manual R installation is still being refactored to be more sand-boxed but this specific issue with `filehash` was resolved.  Closing.
