### ISSUE TITLE
Can not create model groups in standalone GMS

### ISSUE THREAD

**Issue by malachig** [genome/gms#101]
The following command works within TGI but does not work in the sGMS:

``` bash
genome model-group create --models="2891325873,2891325882,2891377978,2891377997" "HCC1395 reference models"
```

Gives the following output:

```
'models' may require verification...
Resolving parameter 'models' from command argument '2891325873,2891325882,2891377978,2891377997'... found 4
ERROR: Class Genome::ProcessingProfile subclassify_by calculation property 'subclass_name' requires 'type_name' in the create() params
Params were: name => 'convergence default' at /opt/gms/TML8B20/sw/ur/lib/UR/Context.pm line 927
```

**Comment by gatoravi** [comment]
Not sure why but this seems to be trying to access a 'processing-profile converge' entry in the database. The name of the processing profile is 'convergence default'

This command lists the processing-profile that we need within the TGI but on the blade it shows up as empty.

``` bash
 genome processing-profile list convergence --filter name='convergence default'
```

We currently don't seem to be exporting this processing-profile in the Genome::Model::Export:Metadata step.

**Comment by ernfrid** [comment]
When modelgroups are created a convergence model is also created. I 
believe this is the processing profile for that model. Perhaps it's not 
being dumped into the sGMS database?

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by gatoravi** [comment]
Currently the metadata exporter dumps all the objects which a clinseq model depends on and their underlying objects recursively. We might have to export this processing profile explicitly.

**Comment by jasonwalker80** [comment]
I believe a recent commit removes the creation of convergence models when a
model group is created.

On Tue, Feb 18, 2014 at 4:42 PM, Avinash Ramu notifications@github.comwrote:

> Currently the metadata exporter dumps all the objects which a clinseq
> model depends on and their underlying objects recursively. We might have to
> export this processing profile explicitly. @sakohthttps://github.com/sakohtmight have an idea on how to best do this.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/genome/gms/issues/101#issuecomment-35444507
> .

## 

Jason Walker
9 Traver Tine Circle
Millstadt, IL 62260
Cell:(618)534-8089

**Comment by ernfrid** [comment]
Looks like genome/gms-core@a72321af552aba1373a1b5ec1e69d237af2396d9 is that commit.

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by gatoravi** [comment]
Thanks @jasonwalker80  and @ernfrid. Pulling in those changes from master seems to allow creation of model groups. I've pushed these to gms-pub here, https://github.com/genome/gms-core/commit/aaf456e4ef6874a9a3b3aa176ec55c986fd81714

**Comment by gatoravi** [comment]
"probably need to make the convergence processing profile part of install even if the user doesn't import any data.  Lots of things will fail without it."

Looks like model group creation works without creating convergence models now, but why was the decision to remove creation of convergence models made ? Are there other commands like this which might depend on this processing profile ? if yes, should we import that processing profile or should we merge in more changes from 'master' which remove the creation of convergence models for other commands ?

**Comment by malachig** [comment]
Hopefully the next merge of gms-core master into gms-core pub will resolve these ambiguities.

**Comment by malachig** [comment]
This appears to have been resolved with the merge.  Model-groups can now be created, listed, etc. without warnings or errors.  Closing now.
