### ISSUE TITLE
Document the schema differences between the sGMS database and the TGI databases.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#109]
The schema inside the TGI is different from the schema in the sGMS. This issue is an effort to document those differences. Differences in schema cause problems whenever there is a merge between the 'master' and 'gms-pub' branches due to missing or additional columns/tables referenced in the code.

**Comment by gatoravi** [comment]
The way to dump the table schemas within the tgi is as follows

```
%ssh gms-postgres
%pg_dump -s genome --username gms-user --host gms-postgres -N sqitch -N workflow -N test_dependencies -N sqitch -T appmanager
```

From Tony,
Use the -N option for pg_dump and  test_dependencies to skip the workflow schema.  Access to that schema is through a different user, and we're not using the workflow schema on postgres anyway.

To get the password(don't run it on the `gms-postgres` host):
`perl -MGenome -e 'print $ENV{GENOME_DS_GMSCHEMA_AUTH}."\n";'`

**Comment by gatoravi** [comment]
the schema dump seems to have some sort of organization I think. The order seems to be this, 
1. schemas
2. tables
3. primary key constraints
3. indexes
4. foreign key constraints. 

move all the schemas, tables, indexes and constraints related to 'workflow' to the end of the file or to a separate file. this will make it easier to see what has changed inside TGI with regards to the database schemas.

**Comment by gatoravi** [comment]
There is a role called "gms-user" doesn't exist in the sGMS, substitute this role to 'genome' in the sGMS perhaps ? will this cause other problems ?

**Comment by gatoravi** [comment]
Genome::Disk:Group needs sticky to be NOT-NULL but  the line `sticky => 1` in the setup/prime-allocations.pl is commented out, any specific reason for this ?

The sticky column has a 'NOT NULL' constraint in the new schema dump, so this value will have to be set during the priming of the databases.

**Comment by gatoravi** [comment]
Genome::Disk::Volume has a property called creation_event_id which is not in the postgres dump, this creates problems while running `perl setup/prime-allocations.pl` during the Make process.
this was added here in response to an RT ticket ,
https://github.com/genome/gms-core/commit/78a0eba20a9f09de95693b34002920991655ad8f

**Comment by gatoravi** [comment]
To create this new dump the following steps were taken, 
1. A new dump was created with the `pg_dump` command referenced above. 
2. All the psql commands related to the 'workflow' schema were copied over to the new dump in the appropriate places in the file(if this is not done and if the workflow commands are added to the end of the file we see warnings related to implicit indexes being created, might be a topic for investigation later). 
3. The 'NOT_NULL' constraint was removed for the column 'sticky' in the disk.group table.
4. The column 'creation_event_id' was added to the disk.volume table.

**Comment by malachig** [comment]
We are currently not aware of any remaining schema related problems.  Closing this issue.
