### ISSUE TITLE
Build IDs in genome model build view are not shown in a sensible order

### ISSUE THREAD

**Issue by malachig** [genome/gms#11]
If I run genome model build view model.id=$mid, I am displayed a list of builds.  These are sorted by UUID and therefore are not in a sensible order.

I believe this has been fixed in the genome/gms-core master branch.  Therefore, merging from master into gms-pub may resolve this issue for standalone GMS testing...

**Comment by sakoht** [comment]
I'll try a merge into gms-pub and see if it works.  If we get past it once we will be part the big changes made around the db conversion, and subsequent updates should be more trivial.

**Comment by malachig** [comment]
This issue has been resolved.  Various fixes merged in during the last merge from gms-core master into gms-core gms-pub have improved the lists of build IDs (and other IDs) that were messed up by the switch from integer only IDs to UUIDs (actually a mix of integers and UUIDs now).
