### ISSUE TITLE
merge symbols in Genome/Disk/Group.pm

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#112]
https://github.com/genome/gms-core/blob/gms-pub-testmerge3/lib/perl/Genome/Disk/Group.pm

Looks like Group.pm has some symbols left(-------, HEAD etc) behind from the merge. Were there conflicts in this file, were they resolved ?

**Comment by malachig** [comment]
I also resolved this. Somehow you are missing a commit... maybe I failed to push something...

**Comment by malachig** [comment]
I kept all the new code plus the old code that defines the 'reads' group. And that seemed to work.

**Comment by gatoravi** [comment]
these have now been removed from the code. closing.
