### ISSUE TITLE
Switch code to use new FTP server for TST1 data and installer data

### ISSUE THREAD

**Issue by malachig** [genome/gms#113]
The old FTP service is being discontinued.  The new setup is described below and is available here:
https://xfer.genome.wustl.edu/gxfer1/project/gms/

We should update all documentation and code that points to the old service to use the new service.

```
#We've modified the cron process that stages your data. It now has "on demand" functionality.

- Update the contents of the source/staging area: /gscmnt/sata102/info/ftp-staging/pub/software/gms/
- Touch "syncme":
   touch /gscmnt/sata102/info/ftp-staging/pub/software/gms/syncme
   watch -n1 ls -l /gscmnt/sata102/info/ftp-staging/pub/software/gms/
- Within 60 seconds, you'll see "syncme" become "syncing"
- When the rsync to the destination completes, "syncing" will be removed.
- Note that even a "No Op" sync operation takes upwards of 4 minutes for filesystem analysis.

Recall the new download location:

https://xfer.genome.wustl.edu/gxfer1/project/gms/
```

**Comment by malachig** [comment]
Replace all instances of:
http://genome.wustl.edu/pub/software/$PATH

With:
https://xfer.genome.wustl.edu/gxfer1/project/$PATH

**Comment by malachig** [comment]
I think I have changed this everywhere in the gms code, install documentation, and wiki pages.  There may be some old closed issues that still refer to the old FTP site but that is fine.  Closing this issue.

I made these changes in both the 'stable' gms branch and the 'test merge' branch so that we are no longer hitting the old FTP server.

ubuntu-12.04:
https://github.com/genome/gms/commit/04744ca611e24af617c3176ca952ca092997dec8
https://github.com/genome/gms/commit/d6b12c702a135191e0405e085bc10654dcd72554

ubuntu-12.04-testmerge3:
https://github.com/genome/gms/commit/d1fb4de2f6597cb38241b9f7323503b1007d8701
https://github.com/genome/gms/commit/7a96734645f38b249785f830d189c70f852a3a46

**Comment by malachig** [comment]
We should test the new syncing procedure described above.  Once that is confirmed to be working smoothly we can close this issue.

**Comment by gatoravi** [comment]
I've tested this procedure with a new apt-dump and it seems to work fine.

**Comment by malachig** [comment]
With the old setup we were mounting the TST1 demonstration data (and optionally doing an rsync) as follows:

``` bash
curlftpfs 'ftp://genome.wustl.edu/pub/software/gms/testdata/GMS1' '/opt/gms/.GMS1.ftp' -o tcp_nodelay,kernel_cache,direct_io
```

But this doesn't seem to work with the new setup:

``` bash
curlftpfs 'ftp://xfer.genome.wustl.edu/gxfer1/project/gms/testdata/GMS1' '/opt/gms/.GMS1.ftp' -o tcp_nodelay,kernel_cache,direct_io 
```

**Comment by malachig** [comment]
Comment from Rob Fugina:

"This should work now, except that we put the new ftp root at the project directory, so do this:

curlftpfs 'ftp://xfer.genome.wustl.edu/gms/testdata/GMS1' '/opt/gms/.GMS1.ftp' -o tcp_nodelay,kernel_cache,direct_io

Seems to work fine for me, though I have to be root for the umount to work.  I'll have to figure that out.

And as I type, our network guy has added the necessary firewall rules for this to work from the outside world.  I've tested it from outside, and it works the same."

**Comment by malachig** [comment]
In order to complete the transition we need to update the entries here in the gms repo:

gms/setup/gms-home-skel/known-systems/GMS1.tsv

From

```
genome.wustl.edu    somekeygms1     initial GMS at TGI  pub/software/gms/testdata/GMS1  pub/software/gms/testdata/GMS1          gmsdata
```

To

```
xfer.genome.wustl.edu   somekeygms1     initial GMS at TGI  gms/testdata/GMS1   gms/testdata/GMS1           gmsdata
```

**Comment by malachig** [comment]
I made the change described above here:
https://github.com/genome/gms/commit/87072485db649cd26711155641af14c80b8fd727

Testing now to make sure the `genome sys gateway attach` and resulting rsync commands work as expected...

**Comment by malachig** [comment]
This seems to be working smoothly.

**Comment by malachig** [comment]
Spoke too soon.  I have been trouble getting a complete sync on clia1 using `genome sys gateway attach`.  It _seems_ to be working, but many files are mysteriously left behind.  The server may have been in a weird state due to recent syncing.  We need to try again and work with systems to see if we can sort this out...

**Comment by malachig** [comment]
This is now working.  Syncing from the new FTP server is working smoothly.  Closing this issue now.
