### ISSUE TITLE
clin-seq build fails due to missing new version of bam-readcount

### ISSUE THREAD

**Issue by malachig** [genome/gms#120]
Since the merge, clin-seq build now now with the following error:
`ERROR: Failed to find executable bam-readcount version 0.5 at /usr/bin/bam-readcount0.5!`

This software is indeed missing.  0.5 is a new version of bam-readcount. It has been packed for Ubuntu precise by @ernfrid but we need to pull this into the sGMS.  This issue should be resolved when our APT repo is updated in issue #119

**Comment by gatoravi** [comment]
The latest apt-dump has version 0.5 of bam-readcount. We need to check if clinseq works with this version.

**Comment by malachig** [comment]
New versions of bam-readcount are now installed in the sGMS:

```
sudo apt-cache policy bam-readcount*
bam-readcount0.3:
  Installed: (none)
  Candidate: 0.3.0
  Version table:
     0.3.0 0
        900 file:/opt/gms/0HDDD95/sw/apt-mirror-min-ubuntu-12.04-2014.03.24/mirror/repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main amd64 Packages
bam-readcount0.4:
  Installed: 0.4.4
  Candidate: 0.4.4
  Version table:
 *** 0.4.4 0
        900 file:/opt/gms/0HDDD95/sw/apt-mirror-min-ubuntu-12.04-2014.03.24/mirror/repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main amd64 Packages
        100 /var/lib/dpkg/status
bam-readcount0.5:
  Installed: 0.5.1
  Candidate: 0.5.1
  Version table:
 *** 0.5.1 0
        900 file:/opt/gms/0HDDD95/sw/apt-mirror-min-ubuntu-12.04-2014.03.24/mirror/repo.gsc.wustl.edu/ubuntu/ lucid-genome-development/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by malachig** [comment]
With the resolution of issue #119, this issue is also now resolved.  Closing.
