### ISSUE TITLE
Rename processing profiles

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#129]
Processing profiles imported into sGMS currently read:
chromosome-fastas
cuffcompare/cuffdiff 2.0.2 protein_coding only
imported-annotation.ensembl
imported-variation-list
infinium wugc
Nov 2011 Default Reference Alignment
November 2011 Clinical Sequencing
Oct 2012 Default Somatic Variation Exome -- DV2 filter params bug fix
Oct 2012 Default Somatic Variation WGS -- DV2 filter params bug fix
October 2012 Default Ovation V2 RNA-seq

Some of these are not meaningful to an external user and the name appears more historical than they actually are.

**Comment by malachig** [comment]
I fixed these and created a record of the changes here: `gms/setup/bin/clean-metadata-file`

When a new metadata file is created we will have to remember to run this clean up.

**Comment by malachig** [comment]
I also renamed the exome capture reagent name to the much more human readable `NimbleGen v3 Capture Chip Set`

**Comment by malachig** [comment]
Closing this issue for now
