### ISSUE TITLE
Add some missing software to genome-snapshot-deps for precise and rebuild

### ISSUE THREAD

**Issue by malachig** [genome/gms#133]
The following can be added to genome-snapshot-deps for precise and should install cleanly in precise: `joinx1.8`, `bam-window`, `seqgrind`, `breakdancer1.4.1`, `breakdancer1.4.2`, `pairoscope0.4`, and `pindel0.2.5`.

These were tested in the sGMS using the following APT source:
`deb http://repo.gsc.wustl.edu/ubuntu lucid-genome-development main non-free`

@gatoravi will update genome-snapshot-deps for all of these and rebuild our APT repo for sGMS.

**Comment by gatoravi** [comment]
a new dump with `joinx1.8`, `bam-window`, `seqgrind`, `breakdancer1.4.1`, `breakdancer1.4.2`, `pairoscope0.4`, and `pindel0.2.5` was created and uploaded to the FTP server(2014.03.17). This is being tested now.

**Comment by gatoravi** [comment]
a fresh install with the above packages completed without errors on a VM install. The Makefile has been updated to use this fresh tar ball here, https://github.com/genome/gms/commit/6d80e91bc6e3a9d3a25526f094a14d7d2e8fd945

**Comment by malachig** [comment]
We have not observed any issues with these new dependencies.  Closing this issue.
