### ISSUE TITLE
Package 'libapache2-mod-fastcgi' has no installation candidate

### ISSUE THREAD

**Issue by ghost** [genome/gms#135]
E: Package 'libapache2-mod-fastcgi' has no installation candidate
make[1]: **\* [done-host/pkgs] Error 100
make[1]: Leaving directory `/home/ubuntu/gms'
make: **\* [all] Error 2

**Comment by ghost** [comment]
The above error message happens for me during installation.  I'm trying the following sequence of commands to fix the install halfway through. 

``` shell
sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu precise main restricted universe multiverse"
sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu precise-updates main restricted universe multiverse"
touch done-host/etc
make
```

If this works, we may consider making these commands part of the automated installation processes.

**Comment by malachig** [comment]
This sounds like a conflict between the way APT sources are configured in your environment (openstack?) and what is expected by the sGMS (basically a vanilla Ubuntu install with a few APT sources added during the sGMS make process).

Following the approach described here to scrub existing APT configuration before installing the sGMS should resolve this issue.

https://github.com/genome/gms/blob/ubuntu-12.04/setup/system_tests/clia1

**Comment by malachig** [comment]
I believe this is resolved.  Closing now.

**Comment by ghost** [comment]
I think the issue may be particular to the ubuntu cloud image that is being used on openstack.  I was not able to recreate the issue on new installs of ubuntu desktop or ubuntu server.  I'll try to confirm the issue using the ubuntu cloud image under vagrant.

**Comment by ghost** [comment]
I can reproduce this issue on the vagrant-ready ubuntu cloud image vm running on my workstation and on openstack.

**Comment by gatoravi** [comment]
I see this issue on a docker install as well. This is my /etc/apt/sources.list

``` bash
jdoe@eb5756cc929c:~/gms$ cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu precise main universe
deb http://archive.ubuntu.com/ubuntu precise-updates main universe
deb http://archive.ubuntu.com/ubuntu precise-security main universe
```

**Comment by gatoravi** [comment]
Doing this `sudo cp -f setup/system_tests/sources.list /etc/apt/` mentioned here, https://github.com/genome/gms/blob/ubuntu-12.04/setup/system_tests/clia1 helps find the right sources. Looks like some versions of precise come with a different sources.list compared to others. Understanding when this happens might help us decide whether to make this step a part of the regular install. So far its been observed on the ubuntu-cloud-image, openstack and docker. (3 great buzzwords right there btw)

**Comment by ghost** [comment]
When I observed this issue on openstack, the vm instance was running the ubuntu-cloud-image version of ubuntu.  I was able to recreate the issue on vagrant by using the ubuntu-cloud-image there.  When you saw this issue with Docker, were you using the ubuntu-cloud-image?

Is there any reason that we should not change the installation to always copy our sources.list over `/etc/apt/sources.list`?

**Comment by malachig** [comment]
We could certainly try that.  I added it to the repo with that thought in mind.  I got it from the Ubuntu precise image from Vagrant.  It seems to have a much more inclusive list of APT repos.  The install also seems to work smoothly when we use the latest Ubuntu 12.04 Desktop iso image.

**Comment by gatoravi** [comment]
I was just using the base ubuntu image on Docker. https://index.docker.io/_/ubuntu/  The only reason that I can think of not to do it is if the user has a customized `sources.list`. We wouldn't want him/her to lose those changes. Wonder what @kindjal thinks ?

**Comment by malachig** [comment]
This should be resolved by this commit:
https://github.com/genome/gms/commit/8a7c740a11ca1bb760afbee3958334f669f00525

APT sources are now more completely configured from files stored in the gms repo.  This should reduce the chances of APT config issues when installing on slightly different flavors of Ubuntu 12.04 images.  Closing this issue now.
