### ISSUE TITLE
make vminit and make vm fail - "vboxsf file system is not available"

### ISSUE THREAD

**Issue by malachig** [genome/gms#136]
I am now getting the following error when attempting to install the sGMS in a VM on my MacPro Desktop.  The problem seemed to coincide with an update of VirtualBox to the latest version: `4.3.10 r93012`:  

```
Failed to mount folders in Linux guest. This is usually beacuse
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` /vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant
```

Based on that error, I'm wondered if the vagrant guest additions update plugin `vagrant-vbguest` is not compatible with this version of VirtualBox. 

Or it may be that the latest version of VirtualBox is not compatible with the the Ubuntu image I am using...

```
Vagrant 1.3.5
Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
```

**Comment by malachig** [comment]
Updating to the latest version of Vagrant: `Vagrant 1.5.1` did not help.

**Comment by gatoravi** [comment]
Is this during the `make vminit` step ?

**Comment by malachig** [comment]
Note to test the automated installation of VirtualBox and Vagrant on a Mac you should download the DMGs for the currently installed version of each of these and use the uninstall tool that comes with it.  Then you should `rm -fr /tmp/gms-install-done-local/`.  Then from a fresh gms checkout, run 'make vminit'.

You should be prompted to install VirtualBox and then vagrant.

**Comment by malachig** [comment]
This does seem to be related to the `vagrant-vbguest` plugin.  If I add `config.vbguest.auto_update = false` to the Vagrantfile before running `make vminit`, the update to VirtualBox Guest Additions is skipped and the Make succeeds...

**Comment by malachig** [comment]
Similarly, downgrading to `VirtualBox 4.3.8 r92456`, also resolves this issue.  This is apparently a compatibility issue between:
`vagrant-vbguest` and `4.3.10 r93012` and this Ubuntu 12.04 image: `precise64 http://files.vagrantup.com/precise64.box`.

For now the solution is to install 4.3.8 and ignore prompts to update to 4.3.10.  Another solution could be to abandon updating the VirtualBox guest additions.  I will submit an issue to the `vagrant-vbguest` project here: https://github.com/dotless-de/vagrant-vbguest

**Comment by malachig** [comment]
Created an issue over at vagrant-vbguest here: https://github.com/dotless-de/vagrant-vbguest/issues/116

**Comment by malachig** [comment]
It looks like this is now a known issue with VirtualBox 4.3.10 and not related to the vagrant-vbguest plugin.  

VirtualBox issue here:
https://www.virtualbox.org/ticket/12879

**Comment by malachig** [comment]
It looks like there is new version of VirtualBox guest additions that will resolve this issue, as will the next version VirtualBox.  The next time we update automatic installation of VirtualBox by the sGMS makefile we should proceed directly to VirtualBox >= 4.3.11.  Closing this issue.
