### ISSUE TITLE
during installation: touch: cannot touch `/opt/gms/test': No such file or directory

### ISSUE THREAD

**Issue by ghost** [genome/gms#138]
While installing sgms on ubuntu desktop, server, and a vagrant-ready copy of ubuntu cloud image, I receive the following error during make:

``` shell
# set permissions on the root directory above the GMS home so that additional systems can attach
sudo touch /opt/gms/test
touch: cannot touch `/opt/gms/test': No such file or directory
make[1]: *** [done-host/gms-home] Error 1
make[1]: Leaving directory `/home/vagrant/gms'
make: *** [all] Error 2
```

Issuing the following command fixes the problem and continues the installation process:

``` shell
sudo mkdir /opt/gms; sudo chown $USER.$USER /opt/gms; make
```

**Comment by gatoravi** [comment]
I've had this problem when I've had disk images left over from a previous install on a VM. Running `vagrant destroy` before the install usually helps for me and removes all the previous ".vdi" files. Do you think this might be the case for you ?

**Comment by ghost** [comment]
The situation that I'm dealing with might be different.  While I am using vagrant, these problems were experienced on newly initialized vagrant boxes.

**Comment by malachig** [comment]
@mkiwala-g can you still reproduce this error?

**Comment by ghost** [comment]
Yes -- I just reproduced it over the weekend on my workstation.  Have many others been attempting the install on a precise64 image hosted with VirtualBox/Vagrant?  I'll see if I can reproduce it using Vagrant on my laptop.

**Comment by malachig** [comment]
I have done it many times on my MacPro laptop and on my Mac Desktop.  I have also done a vagrant install on blade16-4-16.  But I haven't been able to produce that error.

**Comment by ghost** [comment]
I just recreated the issue on my MacBook Pro laptop, using Vagrant 1.4.3 and VirtualBox 4.6.3.

My steps were to initialize a new precise64 Vagrantfile, then boot and log into the vm.  Then on the vm and perform the following steps:

```
1  ls
2  sudo apt-get update
3  set -o vi
4  sudo apt-get dist-upgrade
5  sudo apt-get install git ssh make
6  git clone https://github.com/genome/gms.git
7  cd gms/
8  make
```

Since I can recreate the issue on another host, I believe this issue deserves more investigation.

**Comment by ghost** [comment]
The `/opt/gms` directory is created by the `done-host/gms-home-raw` target if the directory does not already exist.  It appears by this code, the `done-host/gms-home-raw` would not be executed when running in a typical Vagrant virtual machine because the `/vagrant` directory will exist, preventing the `/opt/gms` directory from being created.

``` make
        # the creation of /opt/gms varies depending on whether this is a VM or not
        [ -e /vagrant ] || make done-host/gms-home-raw
        # set permissions on the root directory above the GMS home so that additional systems can attach
        sudo touch /opt/gms/test
```

**Comment by malachig** [comment]
@mkiwala-g, was there a resolution for this issue?  It sounds like you are creating a precise64 VM without using `make vminit` and then encountering this issue.  Is there a way to cover this install path within the Makefile that would not affect the documented method of installing via vagrant?  Or is this perhaps an issue that can be resolved by improving the install docs?

**Comment by ghost** [comment]
I no longer run into this issue.  I can't find any code changes that would appear to have resolved this issue.  One possibility could be that I was using an earlier point release, but I not confirmed that.

**Comment by malachig** [comment]
Ok, I'm closing for now.  We can always re-open if it crops up again.
