### ISSUE TITLE
Document installation of the GMS using Docker

### ISSUE THREAD

**Issue by malachig** [genome/gms#141]
Describe the current procedure for installation of the GMS via Docker.  Create an Ubuntu docker image with modifications that allow the GMS installation to proceed without problems.  Share this Ubuntu docker image.  

Once this is working, create a wiki page describing the step-by-step procedure for firing up the GMS using Docker.  If it is simple enough, a section could also be added to the main installation page of the wiki.

**Comment by gatoravi** [comment]
A separate dev branch "docker-test" was created to test the docker installation. 
Install steps specific to docker:

``` bash
#steps to run before installing on a docker image
dockerinit:
    sudo addgroup fuse #fuse currently doesn't run out of the box on Docker
    sudo umount /etc/hosts #/etc/hosts is read-only by default on docker
dbinit:
        sudo /etc/init.d/postgresql restart #docker doesn't seem to start the postgres server automatically after the install.
```

This branch  was tested by running 

``` bash
make dockerinit
make
```

This was done on a docker image which was basically a base ubuntu image with a temporary user 'jdoe'. Git, ssh, make and vim were installed to make it easier for the users. The permissions of /tmp were changed to 1777 `chmod 1777 /tmp/` to aid the install process, else there are permissions issues. This image was then saved under the name "sgms_jdoe".

**Comment by gatoravi** [comment]
Right now the install process on docker  looks like this, this will be written up into a more formal document once we have tested the capabilities of docker to run builds etc.
1. Install docker - refer here - http://docs.docker.io/en/latest/installation/ubuntulinux/ - docker works best on Linux on a recent kernel. Installing on a Mac is a bit of a hack.
2. `sudo docker pull gatoravi/sgms_jdoe`
3. `sudo docker run --privileged -i -t gatoravi/sgms_jdoe /bin/bash`

This will get you into the docker image.
1. `sudo -i -u jdoe` - change user to jdoe.  
2. `git clone https://github.com/genome/gms -b docker-test` - clone the gms repo
3. `cd gms; make dockerinit; make` - this should install the gms.

**Comment by malachig** [comment]
@gatoravi let's move this documentation to the Wiki and close this issue.

**Comment by gatoravi** [comment]
This is here, https://github.com/genome/gms/wiki/GMS-Installation-on-Docker

**Comment by malachig** [comment]
Since this has been moved to a tutorial on the Wiki I am closing this issue now.  Nice job @gatoravi
