### ISSUE TITLE
empty microarray CNV plots on clinseq-builds.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#143]
The clinseq builds have not CNV plots. This is because the microarray files "tumor.copynumber.original" and "normal.copynumber.original" have a different format on the sGMS compared to TGI. The wrong columns are then used by the tool to call CNV's.

**Comment by malachig** [comment]
@gatoravi what ever happened with this issue?

**Comment by gatoravi** [comment]
this was fixed in master but not merged into gms-pub. I cherry-picked this change here https://github.com/genome/gms-core/commit/466aaafedd68cba0d43afda20ad9e3e75ea80b39 
A new clinseq model build was run and the plots are generated correctly now. Closing this issue.
