### ISSUE TITLE
minor issues with tutorial on importing data

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#144]
I attempted the tutorial on importing data here from within the pre-configured VM:
https://github.com/genome/gms/wiki/Beginner%27s-Guide-to-Data-Import

There were a few minor issues:
1) The VM does not currently contain:
~/gms/downsampled-demo-data/
where the referenced scripts live. I had to do a git fetch/pull on the gms repo to get it. VM should be updated!

2) The 'source-files' path specified in the example is not valid since the downsampled data will not be in the current working directory by default. However, if the user is operating in the pre-configured VM or has run the ./setup/prime-system.pl script as instructed (and selected the downsampled bams) then they will exist at /opt/gms/bams/hcc1395_1tenth_percent/. Instead it might be more logical to get the user to download the bams in this tutorial, even if it is redundant with other tutorials.

3) When importing instrument data using the sample command at the following error appears:
Useless use of private variable in void context at (eval 1183) line 6.

4) The specified genome model clin-seq advice command doesn't currently work because the VM doesn't yet have the update Advise.pm code. I had to do a git fetch/pull on genome to get it. VM should be updated!

5) The style of naming of individual, samples, libraries and instrument is not consistent between the manual example and what is actually done in the script.

6) We should mention that a helper tool is under development to take users from a spreadsheet type list of samples/libraries through a successful import.

**Comment by obigriffith** [comment]
I have rerun the import tutorial. It works much better now. I still see the error discussed above in (3). Namely, during import of instrument data steps I get:
Useless use of private variable in void context at (eval 1183) line 6.

One other thought - why not have the example shown on the tutorial page be the first set of commands from each step rather than the last?  Wouldn't this seem more logical. The user would immediately recognize that they already entered the first set of commands and now here are X more that follow the same pattern. Rather than having to scroll down to bottom of the list of commands to make that connection.

**Comment by ghost** [comment]
I can look into the warning.

I agree, having the example always be the first block of code would be simpler.  We just have to make sure that the first instrument data import command corresponds to the first library creation command and the first sample creation command.  I'll can make these changes as well.

**Comment by ghost** [comment]
I have [fixed](https://github.com/genome/gms-core/commit/ce44f55461186053d4165461779c974261dfb992#diff-1fcf415156ce8c3b7654a31bbd445b20) the code to not throw a warning message during instrument data import.  The wiki has been updated to always use the first genome command from each section of the script.

**Comment by ghost** [comment]
I believe that this issue has been resolved.
