### ISSUE TITLE
Test sGMS install on OpenStack and provide specific instructions (tutorial) for using OpenStack

### ISSUE THREAD

**Issue by malachig** [genome/gms#146]
We should document our experiences with running the sGMS on OpenStack and provide a clear path to get a new user (internal to TGI or external) up and running on this platform.

**Comment by ghost** [comment]
I've posted some [documentation](https://github.com/genome/gms/wiki/Developers-guide-to-installing-the-GMS-on-an-OpenStack-instance).

Please review it.  Would you like me to link it from the list [here](https://github.com/genome/gms/wiki/Documentation#for-gms-developers)?

**Comment by malachig** [comment]
This looks great. Nice job. Yeah, let's post this in the developer's
documentation section beside the one for Amazon AWS.

Malachi

**Comment by ghost** [comment]
The new documentation has been linked in the developer's documentation section beside the one for Amazon AWS.  I believe that resolves this issue.
