### ISSUE TITLE
Document creation of certain auxiliary data used in the GMS

### ISSUE THREAD

**Issue by malachig** [genome/gms#147]
It would be nice (both for internal GMS users/developers and external users) if we had documentation covering some use cases related to auxiliary annotation data used in the GMS.  For example,
- How do I create a modified reference genome build based on an existing one?  For example, say I want to do alignments against human reference build37 with a virus sequence added.
- How do I import an entirely new version of the human reference genome? e.g. hg20/build38
- How do I import a new version of dbSNP? Or more generically, any feature set that I want to import and use in the GMS?
- How do I import a new version of human Ensembl transcript annotations to be used for annotating variants, rna-seq analysis, etc.?

Perhaps some or all of this documentation already exists?  If not, perhaps it could be added to Confluence within TGI and mirrored in the sGMS wiki for the benefit of potential users.

**Comment by ghost** [comment]
I've rounded up some internal documentation which answers many of these questions.  I'm reviewing the documentation to see what I could adapt for posting to the wiki on github.

**Comment by ghost** [comment]
As documentation is tested, I'm moving it [here](https://github.com/genome/gms/wiki/Auxiliary-Data-Import).

**Comment by ghost** [comment]
The documentation for importing references and dbsnp have been posted.

Ensembl imports will not be quite as straightforward, and will require more time.

**Comment by malachig** [comment]
@mkiwala-g are you done with this task for now?  We can always ask for more documentation, but I think we have covered most of the critical areas now...

**Comment by ghost** [comment]
@malachig, I'm working on documentation for the Ensembl annotations based on importing the GRCh38 reference genome and then importing the homo_sapiens_core_76_38 ensembl database.   

I have not yet gotten this working yet myself, so these steps are incomplete, but a rough outline might be:
- Install and setup mysql
- load mysql with an ensembl database
- choose and download ucsc tiering and conservation information
- modify ReferenceSequence.pm to relate the GRCh38 imported reference sequence id to the file system locations of the downloaded tiering and conservation data
- run genome model define imported-annotation

All of the other documentation is complete.  If you do not wish to have this Ensembl documentation at this time, then this issue can be closed.

**Comment by ghost** [comment]
@malachig I should have also mentioned that this documentation would target a "developer" audience since following this documentation would require some coding in order to have the ensembl annotations imported.

**Comment by ghost** [comment]
It turns out that I'll need to develop this documentation anyway.  I leave it up to you whether to close this issue now or not.

**Comment by malachig** [comment]
Ok, that will be most welcome.  Leaving open for now.

**Comment by ghost** [comment]
I expanded the documentation to include Ensembl annotation importing.  Resolving.

**Comment by ghost** [comment]
Should have mentioned that genome/gms-core@73c5a76eb31d8e556810e8d57a68e5fd65aaf1d0 was necessary to make the Ensembl import work.
