### ISSUE TITLE
When installing sGMS via `make vminit` the installer only support certain host systems - make this clear

### ISSUE THREAD

**Issue by malachig** [genome/gms#148]
Currently if you want to install sGMS inside a VM automatically using vagrant you can do so and it will walk you through the process of installing Vagrant and VirtualBox, then adding an Ubuntu12.04 box VM, logging into that machine and running the rest of the make process.  This works by installing as follows: `make vminit; vagrant ssh; make`. 

This only works when the host system is: Mac OSX (darwin), Ubuntu10.04, or Ubuntu12.04.  The reason is this.  The following make targets are executed: vminit -> vmup -> vmcreate -> done-host/addbox -> done-host/vminstall -> done-host/vminstall-*. 

Where \* is resolved automatically in the makefile to the OS vendor/version.  Only three options are supported: `vminstall-Darwin`, `vminstall-Ubuntu10.04`, `vminstall-Ubuntu12.04`.  If your host is not one of these you get an error like:

```
make: *** No rule to make target `done-host/vminstall-Debiantesting'. Stop.
make: *** [done-host/vminstall] Error 2
```

We should make this more clear by adding a check to `done-host/vminstall` so that the user is clearly warned and the make is aborted if their system is not supported.

If their system is not supported they have several options available to them:
- Create a new `done-host/vminstall-*` make target for their system
- Create an Ubuntu12.04 virtual machine instance by their own method, log in and run the installation using the Ubuntu12.04 instructions.

**Comment by malachig** [comment]
@gatoravi did you have a chance to look at this?

**Comment by gatoravi** [comment]
Sorry forgot to update here, 

This is dealt with [here](https://github.com/genome/gms/commit/d6e1032ccca119e9cd3fa7ff5d0464bcd7d6ec9b), the installer exits with an error if the host OS is unrecognized.

**Comment by malachig** [comment]
Ok thanks.  Closing this now then.
