### ISSUE TITLE
Test sGMS install on Amazon EC2

### ISSUE THREAD

**Issue by malachig** [genome/gms#149]
First pass, attempting install with a Community AMI of Ubuntu 12.04:
- Log into AWS console
- Find the EC2 dashboard
- Hit the 'Launch Instance' button
- Find the following AMI in the 'Community AMIs': `ubuntu/images/hvm-ssd/ubuntu-precise-12.04-amd64-server-20140606` aka `ami-3daad70d`
- Start EC2 instance type: m3.2xlarge (8 cpus, 30 Gb ram, 80 Gb ssd storage)
- During the creation of this instance, create a new 'key pair' in the AWS console.  Save the 'private key file' somewhere handy with some name: e.g. `sgms-private-key.pem`.  
- Limit read permissions for this file as follows: 

```
chmod 600 sgms-private-key.pem
```
- Make sure the 'Security Group' for the instance is set to 'launch-wizard-1' (or an appropriate security group you have configured that allows ssh connections).
- Find the Public DNS for your instance in the AWS console.  e.g. `ec2-53-121-44-13.us-west-2.compute.amazonaws.com`.  You may have to select the instance to bring up the expanded view of instance details below.
- Login as follows: 

```
ssh -i sgms-private-key.pem  ubuntu@ec2-53-121-44-13.us-west-2.compute.amazonaws.com
```
- If you see an error and fail to login, most likely you forgot the `ubuntu@` part of the login command or failed to change the permission on your key file.
- Set a password for the ubuntu user by: 

```
sudo passwd ubuntu
```
- setup opt where all data will go: 

```
sudo umount /mnt; cd /; sudo mount /dev/xvdb /opt;
```
- make this mount persistant by replacing the existing /dev/xvdb entry in '/etc/fstab' with: 

```
/dev/xvdb /opt  auto  defaults,nobootwait,comment=cloudconfig 0 2
```
- Update debian repos: 

```
sudo apt-get update
```
- Install git, ssh, make: 

```
sudo apt-get install git ssh make
```
- Set ownership of the working space: 

```
sudo chown -R ubuntu:ubuntu /opt
```
- Move to local storage mount: 

```
cd /opt; mkdir src; cd src
```
- Get sGMS installation repo from github: 

```
git clone https://github.com/genome/gms.git
```
- Run make: 

```
cd /opt/src/gms
make
```
- logout and login again
- To get this far you need an EC2 instance with 5 Gb for the OS and an additional 10Gb for the sGMS install (in this example the entire sGMS lives on a separate mount).
- Complete sanity checks and database priming at: https://github.com/genome/gms/wiki/Install
- Prime the system with basic database entries, reference sequences, test data, etc.  To do this you will need at least XXGb of storage on the EC2 instance:

```
cd /opt/src/gms
./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=rsync --low_resources --memory=32gb
```

**Comment by malachig** [comment]
Next steps:

1.) _AMI creation_.  Create and save an AMI that streamlines the installation above.  We want to provide an AMI that the user can log into, clone the repo, and type `make` with as little preamble as possible.  This will mean among other things setting a password for the ubuntu user (we can use 'sgms'). 

2.) _sGMS Amazon tutorial creation_.  Create a detailed tutorial with screenshots of every step that explains how to log into Amazon, create an EC2 instance, obtain domain name from the EC2 dashboard, set up AWS authentication and security, login to the instance from a terminal, install the sGMS system, and once done, how to log out and destroy the Amazon instance.

3.) _Cost analysis_
It would be nice to determine the costs of doing the following (back of the envelope estimates included in brackets):
- Run the sGMS installation ($1.00)
- Also load all auxiliary data such as the reference genome, etc. ($5.00)
- Do the test analysis on down sampled data ($50.00)
- Do an analysis with full size data, but Exome only ($200.00)
- Do the complete HCC1395 WGS, Exome, RNA-seq analysis ($1500.00)

For each of the scenarios above we also want to recommend the minimum EC2 instance type that would be required for that analysis to succeed.  To help track costs and instance types, every time you create a new instance be sure to tag it with descriptive tags for that test.

@gatoravi do you want to take a first crack at these tests?

**Comment by gatoravi** [comment]
Installation completes succesfully on SGMS_INSTALL_V1 (ami-e9ee95d9, region = "US - West[oregon]" ) using a "m3.2xlarge" instance.
Note - this instance type is not sufficient to run the demo analysis.

**Comment by ghost** [comment]
@gatoravi On OpenStack I was able to run most of the builds against the 0.1% downsampled TST1 data using an "m1.2xlarge" instance flavor.  To get around only having 160GB of disk storage, I attached two additional volumes to the instance (1 TB of /tmp space and another 1TB mounted on /opt).  Perhaps something similar would work on amazon.

The only reason that I didn't run all of the builds was that the last build I needed to do was interrupted by a maintenance outage, not because of a demonstrated lack of resources of the m1.2xlarge instance flavor with extra storage attached.

**Comment by gatoravi** [comment]
Thats a great suggestion ! Any ideas on how to automate the attaching of the volumes ?

**Comment by ghost** [comment]
I haven't tried automating the process of attaching the volumes.  For the space on /tmp, in OpenStack while I'm configuring my instance, I'm given the option to set my "Instance Boot Source" to "Boot from Image (Creates New Volume)", and I am able to specify that the new volume is 950GB in size (so not quite 1TB).  That's how I handle /tmp.

If amazon gives you this option, you may be able to ask for 2TB when setting up the instance boot source.  I had problems with asking for 2TB in OpenStack, so I had to separately allocate a second volume for /opt.  If you do not run into the problem, you would not need to worry about automating the attaching of the volumes because the storage would be available immediately without additional steps.

**Comment by malachig** [comment]
Results from AWS EC2 tests using the complete HCC1395 exome data set.  Priming data takes ~3-4 hours.  Analysis times as follows:

_i2.2xlarge_
model name  start time  end time    time length (hh:mm)
hcc1395-tumor-snparray  8/14/14 18:25   8/14/14 18:52   0:26
hcc1395-tumor-refalign-exome    8/14/14 16:20   8/15/14 10:08   17:48
hcc1395-somatic-exome   8/15/14 15:00   8/16/14 1:29    10:29
hcc1395-normal-snparray 8/14/14 18:25   8/14/14 18:52   0:26
hcc1395-normal-refalign-exome   8/14/14 16:20   8/15/14 7:33    15:12
hcc1395-clinseq 8/18/14 1:22    8/18/14 3:38    2:16
total analysis time         20:30

_i2.8xlarge_
model name  start time  end time    time length (hh:mm)
hcc1395-tumor-snparray  8/14/14 18:25   8/14/14 18:41   0:15
hcc1395-tumor-refalign-exome    8/14/14 16:20   8/15/14 8:26    16:05
hcc1395-somatic-exome   8/15/14 14:59   8/15/14 21:42   6:42
hcc1395-normal-snparray 8/14/14 15:53   8/14/14 16:09   0:15
hcc1395-normal-refalign-exome   8/14/14 18:27   8/15/14 7:41    13:13
hcc1395-clinseq 8/18/14 1:17    8/18/14 3:29    2:11
total analysis time         18:33

Install, priming and run time is ~24 hours for HCC1395 tumor/normal exome data.  Estimated cost for these instance types:
Type    vCPU    ECU Memory (GiB)    Instance Storage (GB)   Linux/UNIX Usage
i2.2xlarge  8   27  61  2 x 800 SSD $1.705 per Hour   -> $40.92
i2.8xlarge  32  104 244 8 x 800 SSD $6.820 per Hour   -> $163.68

**Comment by malachig** [comment]
We now have an AMI that is ready and tested for installation of the sGMS in all 8 Amazon EC2 regions.  In all cases, the AMI is named 'SGMS_INSTALL_V1'.  To do the exome analysis it seems that   the instance type 'i2.2xlarge' is a good place to start.  A tutorial create by @gatoravi clearly documents how to do the installation using Amazon AWS.  This can be found here:

https://github.com/genome/gms/wiki/Beginners-Guide-to-installing-the-GMS-on-an-Amazon-Web-Services-(AWS)-Instance

**Comment by malachig** [comment]
Testing of the GMS on AWS EC2 is going smoothly.  Since we have accomplished the initial task of getting the install to happen smoothly and all tests with real data have completed successfully I am closing this issue.
