### ISSUE TITLE
Make a tutorial that describes how to create new processing profiles based on existing ones

### ISSUE THREAD

**Issue by malachig** [genome/gms#151]
Using examples from ref-align, somatic-variation and rna-seq create a tutorial that explains how to modify an existing pipeline in various ways:

For example, 
- create a reference-alignment processing profile with modified read aligner parameters.
- create a WGS somatic-variation processing profile that drops the SV detection step
- create an rna-seq processing profile that uses additional CPUs for alignment and expression estimation

**Comment by gatoravi** [comment]
An initial version of this tutorial is [here](https://github.com/genome/gms/wiki/How-to-create-new-processing-profiles-based-on-existing-ones-%3F)

**Comment by malachig** [comment]
@gatoravi this is a great start.  It looks like comments explaining each step and screenshot from the somatic-variation example onwards still need to be added.

**Comment by gatoravi** [comment]
ok this is done. please have a look. closing for now, re-open if anything.
