### ISSUE TITLE
vm vagrant install fails with rake-10.1.1 error

### ISSUE THREAD

**Issue by malachig** [genome/gms#155]
Trying to complete installation on a Mac pro using VirtualBox and Vagrant installation option.  Getting this error:

```
/vagrant
cd /var/www/gms-webviews &&  sudo -u www-data bundle exec bundle exec rake assets:precompile && cd -
Could not find rake-10.1.1 in any of the sources
Run `bundle install` to install missing gems.
make: *** [done-host/rails] Error 7
make[1]: *** [setup] Error 2
make[1]: Leaving directory `/vagrant'
make: *** [all] Error 2
```

**Comment by malachig** [comment]
The source of this error is not immediately obvious.

```
cd /var/www/gms-webviews
bundle install
```

shows `Using rake 10.1.1`

I'm guessing this is some issue relating to multiple versions of Ruby ... 

```
head -n1 $(which bundle)
#!/usr/bin/ruby1.9.1

ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

**Comment by malachig** [comment]
Here is the make target that is failing:

```
done-host/rails: done-host/pkgs
#
# $@:
#
sudo -v
sudo gem install bundler --no-ri --no-rdoc --install-dir=/var/lib/gems/1.9.1
sudo chown www-data:www-data /var/www
sudo -u www-data rsync -r $(GMS_HOME)/sw/rails/ /var/www/gms-webviews
# cd /var/www/gms-webviews && sudo bundle install
sudo /usr/bin/gem1.9.1 install bundler --no-ri --no-rdoc
sudo -u www-data mv /var/www/gms-webviews/config/database.yml.template /var/www/gms-webviews/config/database.yml
cd /var/www/gms-webviews && sudo bundle install && cd -
cd /var/www/gms-webviews && sudo -u www-data bundle exec bundle exec rake assets:precompile && cd -
[ -e /var/www/gms-webviews/tmp ] || sudo -u www-data mkdir /var/www/gms-webviews/tmp
sudo -u www-data touch /var/www/gms-webviews/tmp/restart.txt
touch $@
```

Questions, I have.
- Why not use rbenv to manage this ruby app?
- Why are we running `/usr/bin/gem1.9.1 install bundler` and `bundle install` as root?  These commands result in warnings that installing your bundle as root will break this application for all non-root users.  The very next thing we attempt to do is run a rake task as the `www-data` user.   It seems like that may be related to the problem we are having here...  A lot of things are done as root in this install, so perhaps it we are just continuing down that road...
- Why does this command `cd /var/www/gms-webviews && sudo -u www-data bundle exec bundle exec rake assets:precompile && cd -` contain `bundle exec` twice in a row?  Is this equivalent to shelling out within a shell?  If so we may be introducing an environment issue by doing so.

**Comment by malachig** [comment]
It seems that the installation will succeed if I change:

```
cd /var/www/gms-webviews && sudo -u www-data bundle exec bundle exec rake assets:precompile && cd -
```

to

```
cd /var/www/gms-webviews && sudo -u www-data bundle exec rake assets:precompile && cd -
```

Will this cause problems for other installation types?  Why was the double `bundle exec` being used in the first place?  And why was this working for so long, and no longer works now?  Perhaps @acoffman can provide some guidance...

**Comment by sakoht** [comment]
I don't recall the details on this.  I modified some version of the install script @acoffman and Ben were using ...but I'm not blaming them for my butchery. :)

**Comment by acoffman** [comment]
Hrm, I'm not sure why there would be a double `bundle exec`, I definitely wouldn't think that was intentional. Removing it should be safe as far as I know!

**Comment by malachig** [comment]
Ok, thanks @acoffman and @sakoht.  I'm testing this change.  It definitely seems to resolve the issue in the vagrant VM install.  Making sure it also works when installing in an Amazon instance where we are using a slightly different flavor of Ubuntu 12.04.

**Comment by malachig** [comment]
This seems to be working.  Still no explanation of how it was working before or why it stopped working...

Relevant commit: https://github.com/genome/gms/commit/907433ba70f9d56a363ad7f64e07df8aef5be1f3

**Comment by malachig** [comment]
This problem seems to be resolved.  Closing now.
