### ISSUE TITLE
Add notes to the GMS paper regarding ISO/IEC 9126.

### ISSUE THREAD

**Issue by sakoht** [genome/gms#161]
Believe it or not this exists:
http://en.wikipedia.org/wiki/ISO/IEC_9126

**Comment by sakoht** [comment]
I added content to the google doc.  We can move that into the paper or supplementary material as necessary.  It is probably too verbose for the paper.  Perhaps to verbose in general...

**Comment by gatoravi** [comment]
this has been added to the main doc. closing.
