### ISSUE TITLE
dindel-tgi1.01-wu1 dependencies unable to be installed.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#175]
dindel-tgi1.01-wu1 was recently added to the precise deps here https://github.com/genome/genome-snapshot-deps/commit/7e5045dd3a597f3ac6fee75eed26d37a1496ae37

It has a dependency libboost-program-options1.40.0 which is unable to be installed on precise.

```
gmsuser@clia1:~/gms$ apt-cache depends dindel-tgi1.01-wu1
dindel-tgi1.01-wu1
  Depends: <libboost-program-options1.40.0>
  Depends: libc6
  Depends: libgcc1
  Depends: libstdc++6
  Depends: zlib1g
  Depends: python
  Depends: python-support
  Breaks: dindel-tgi1.01
  Replaces: dindel-tgi1.01
```

**Comment by malachig** [comment]
Doh.  In the past @mcallaway has been able to help us understand some of these dependency issues with precise vs. lucid.

**Comment by gatoravi** [comment]
An attempt to address this is here https://github.com/genome/dindel-tgi/pull/1

**Comment by gatoravi** [comment]
The PR is merged in and dindel-tgi1.01-wu1, I had trouble building the package from genome-snapshot-deps on my linus machine, seems to work fine on a precise-box. It might have something to do with the setup on my box. @iferguson90 was able to install it fine on his end. Closing this issue.
