### ISSUE TITLE
refalign fails with error failure to find target_bed.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#178]
```
   455 2015-03-10 22:24:54+0000 ip-172-31-23-19: ERROR: When trying to access target_bed (/opt/gms/GMS1/fs/gc7001/info/model_data/software-result/659bb0d736f4493ca4ddd629f608282c/converted.bed) , we found that         it does not exist or has no size
   456 2015-03-10 22:24:54+0000 ip-172-31-23-19: ERROR: When trying to access target_bed (/opt/gms/GMS1/fs/gc7001/info/model_data/software-result/659bb0d736f4493ca4ddd629f608282c/converted.bed) , we found that         it does not exist or has no size at /opt/gms/L357V43/sw/genome/lib/perl/Genome/Model/Build/ReferenceSequence/ConvertedBedResult.pm line 36.
   457 2015-03-10 22:24:54+0000 ip-172-31-23-19:   Genome::Model::Build::ReferenceSequence::ConvertedBedResult::target_bed('Genome::Model::Build::ReferenceSequence::ConvertedBedResult=H...') called at /opt/gms/        L357V43/sw/genome/lib/perl/Genome/FeatureList.pm line 442
```

convertedbedresult were added as a software result here https://github.com/genome/genome/commit/84d56e0e24f066aca088f9201986b3f141128362

To fix this issue we can either not import the software result objects during the meta-data import or copy-over the required files as has been done for some other software results such as reference-alignment indexes.

**Comment by malachig** [comment]
If they have been added perhaps we might need them down the road?  

Assuming syncing of the ftp is working, it wouldn't be that hard to sync these new results over as well.  We would also need to update the tarball version as well...

**Comment by gatoravi** [comment]
this was added to the staging directory and is now available on the FTP site. a new tarball with these files was also created. instructions on how to do this are [here](https://github.com/genome/gms/wiki/Z-developer-notes)

**Comment by gatoravi** [comment]
closing this.
