### ISSUE TITLE
error while sending a build report email.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#179]
This is new and I'm not sure what really triggered this. The error basically  with validation of the from email address which is set to `apipe@http://localhost` by default. The domain name can be changed by \$GENOME_EMAIL_DOMAIN, not sure if we actually need a real email-address that works or one that just validates.

```
     3 2015-03-13 18:24:38+0000 ip-172-31-19-8: 2015/03/13 18:24:38 Genome::Report::Email: Error in *from* email address: apipe@http://localhost
     4 2015-03-13 18:24:38+0000 ip-172-31-19-8: ERROR: Error in *from* email address: apipe@http://localhost
     5 2015-03-13 18:24:38+0000 ip-172-31-19-8: 2015/03/13 18:24:38 Genome::Model::Build::ReferenceAlignment::Solexa id(0839fce1ad4f49fc8c8d2e80062140f6 §
     6 2015-03-13 18:24:38+0000 ip-172-31-19-8: ERROR: Couldn't email build report (build initialized)
     7 2015-03-13 18:24:38+0000 ip-172-31-19-8: DEBUG: Disconnecting Genome::DataSource::GMSchema default handle.
```

**Comment by gatoravi** [comment]
this looks vaguely familiar and I'm not sure whats going on here. I'd be curious to see if we can replicate it outside AWS. clia1 testing is on hold due to some issues with the box right now, testing on a VM might be another option.

**Comment by gatoravi** [comment]
This was fixed here - https://github.com/genome/gms/commit/be4368bcf5aef9452b18c4fd1a7f890a215c137e
Exim is now stopped before configuring the mail server. After the configuration exim is restarted again. We also get rid of a paniclog file, it is not immediately clear why the panic log appears except that there seems to be contention for the same port amongst multiple services. This seems to be working now though.
This needs to be tested outside clia1.

**Comment by malachig** [comment]
Hi @gatoravi .  I'm running some tests on AWS.  I have run some microarray builds and everything seems to work but the build winds up with a status of `Failed`.  There are no error logs shown when I run `genome model build view` but if I go to the build directory and look here:  `reports/Build_Failed/report.xml` I see the following error:

```
      <error>
        <build-event-id>45aa3bc6258f4138a77f100175163519</build-event-id>
        <stage-event-id>45aa3bc6258f4138a77f100175163519</stage-event-id>
        <stage>all stages</stage>
        <step-event-id>45aa3bc6258f4138a77f100175163519</step-event-id>
        <step>main</step>
        <error>Failed to set build to success: Couldn't email build report (build succeeded)</error>
        <error-wrapped>Failed to set build to success: Couldn't email build report (build
succeeded)</error-wrapped>
        <error-log>/opt/gms/O9W6X85/fs/O9W6X85/info/model_data/2891230328/build95932c805dc94b939b0ab1c525efec89/logs/workflow-server.err</error-log>
      </error>
```

Sounds related to this issue...

If you want to see this error on AWS you can log into this instance in our AWS account:  `GMS merge test instance` (54.148.155.195).  Its in the `Oregon` AWS region.

**Comment by gatoravi** [comment]
this is because the 'from' email address, "apipe@ip-XXX-XXX" fails to validate in Genome::Report::Email.pm, I think a fix for this could be changing the default 'from' address to $ENV{GENOME_EMAIL_NOREPLY}
If you'd like to run through the rest of the builds it should be possible now.

**Comment by sakoht** [comment]
Hey did that Vagrantfile work for you by chance?

**Comment by malachig** [comment]
Hey @gatoravi, it looks like this is working.  Maybe we should commit the change you suggested.  @sakoht I don't think we had a chance to test the Vagrantfile.  Did it get pushed into the repo somewhere?

**Comment by gatoravi** [comment]
Ok, I'll create a PR for the SGMS branch today. update - this is here https://github.com/genome/genome/pull/676
@sakoht 's Vagrantfile is in this issue https://github.com/genome/gms/issues/173, I don't think I have the AWS credentials to try it.

**Comment by gatoravi** [comment]
This PR is now merged in and this issue seems to be resolved.
