### ISSUE TITLE
Failed to run cummerbund

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#182]
Differential expression fails with this error.

```
   112 2015-03-16 21:05:03+0000 ip-172-31-19-8: Error in sqliteExecStatement(con, statement, bind.data) :
   113 2015-03-16 21:05:03+0000 ip-172-31-19-8:   RS-DBI driver: (error in statement: near ")": syntax error)
   114 2015-03-16 21:05:03+0000 ip-172-31-19-8: Calls: getGenes ... dbGetQuery -> sqliteQuickSQL -> sqliteExecStatement -> .Call
   115 2015-03-16 21:05:03+0000 ip-172-31-19-8: Execution halted
   .....
   158 2015-03-16 21:05:03+0000 ip-172-31-19-8: ERROR: Failed to run cummerbund!
   159 2015-03-16 21:05:03+0000 ip-172-31-19-8: Command module died or returned undef.
   160 2015-03-16 21:05:03+0000 ip-172-31-19-8: Genome::Model::DifferentialExpression::Command::Cummerbund failed to return a positive true value (rv = undef)
   161 2015-03-16 21:05:03+0000 ip-172-31-19-8: UnknownPackage: Failed to run cummerbund! at /opt/gms/RGTBV26/sw/workflow/lib/Workflow/OperationType/Command.pm line 379, <GEN13> line 1.
   162
```

**Comment by sakoht** [comment]
It think that cummerbund is R.

Is it installed and installed the same way as at TGI?

**Comment by jasonwalker80** [comment]
There are issues with the R libraries used by cummerbund and incompatibilities with R versions used at TGI.  I can't recall all the specifics, but the current path forward is to use a PP that does not define cummerbund as a part of the DE model:  
https://github.com/genome/genome/pull/558

**Comment by malachig** [comment]
Yes, it is R.  I doubt that it is installed exactly as it is in TGI.  R installation remains a nightmare.  I believe, it is not working within TGI at the moment actually... 

This seems to be relevant:
http://compbio.mit.edu/cummeRbund/faq.html

I suspect that some attempt was made to update CummeRbund and the version we are now attempting to install is no longer compatible with the version of Cuffdiff we are using.  CummeRbund updates seem to be tied to specific versions of Cuffdiff.  And CummeRbund itself has a very nasty dependency tree.  Relying on particular versions of ggplot, plier, etc. to work properly.  I suspect that all of this mess is the reason for this PR in genome: https://github.com/genome/genome/pull/558

I believe this was added so that we could selectively drop CummeRbund from the pipeline and get DE builds to succeed again...

We could fix this problem by taking complete control over the R installation procedure as I have done in the past.  It was a pain to maintain but it seemed the only way I could get all of the R libs locked down enough to keep things stable.

**Comment by gatoravi** [comment]
ok looks like there are two options suggested here,
1. drop Cummerbund from processing-profile and remain consistent with master.
2. try to fix this problem by addressing the issue and maybe this might help with bringing Cummerbund back into TGI processing-profiles at some point.

**Comment by malachig** [comment]
I think option 1 is more practical at the moment.  Based on past experiences trying to work with the CummeRbund dependencies...

**Comment by gatoravi** [comment]
The Differential Expression(DE) processing-profile we'd like to shift to looks like `March 2015 Differential Expression Candidate 1`

I believe the way to do this is to create a new DE model with this processing-profile and update our ClinSeq model to use the new DE model. A new metadata-dump will then have to be created and imported which will pull in the new DE model and the updated DE processing-profile. Is this right?

```
 genome processing-profile describe 25876d817a4b4820bd49b82868536fef
Using libraries at /gscmnt/gc2607/mardiswilsonlab/aramu/test/genome/lib/perl
'processing_profiles' may require verification...
Resolving parameter 'processing_profiles' from command argument '25876d817a4b4820bd49b82868536fef'... found 1
Processing Profile: March 2015 Differential Expression Candidate 1 <ID: 25876d817a4b4820bd49b82868536fef>
type_name: differential expression
differential_expression_mask_reference_transcripts: rRNA_MT
differential_expression_name: cuffdiff
differential_expression_params: --quiet --num-threads 4 --max-bundle-frags 10000000
differential_expression_version: 2.1.1
summarize_differential_expression_name: <NULL>
summarize_differential_expression_version: <NULL>
transcript_convergence_biotypes: protein_coding
transcript_convergence_name: cuffcompare
transcript_convergence_params: {include_contained => 1,generic_gtf_input => 1,generate_tracking_files => 0,}
transcript_convergence_version: 2.1.1
```

**Comment by malachig** [comment]
Yes, that is how we have done it in the past.

**Comment by gatoravi** [comment]
This was done as follows,

```
genome model input show 18177dd5eca44514a47f367d9804e17a
genome model copy abeb5a3cddb94374afffd617684fa49a name=hcc1395-differential-expression-new processing_profile=25876d817a4b4820bd49b82868536fef
genome model rename hcc1395-differential-expression hcc1395-differential-expression-old
genome model rename hcc1395-differential-expression-new hcc1395-differential-expression
genome model input update 18177dd5eca44514a47f367d9804e17a de_model name=hcc1395-differential-expression
genome model export metadata 18177dd5eca44514a47f367d9804e17a > 18177dd5eca44514a47f367d9804e17a.dat
```

The metadata file was updated here, 
https://github.com/genome/gms/commit/3445c52f044fc6cb45db71c606f8e43baa8e35fc

**Comment by gatoravi** [comment]
This processing-profile seems to work now. We no longer use CummerBund in the SGMS.
