### ISSUE TITLE
add sciclone and cn.mops

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#188]
cn.mops and sciclone are now used in clinseq. These are both R packages which need to be installed on the sgms. It looks like all our R packages are installed using the 'renv' method described [here](https://github.com/genome/gms/issues/126). It's currently unclear how to add new R packages using this method.

**Comment by malachig** [comment]
Hey @mcallaway, do you remember how this R package gets built.  It seems like we just install one package `renv` and it dependencies we getting a working R install that is the correct version, is configured properly, has all the linux system dependencies we need (Cairo, etc.) and also has all of the R and Bioconductor libraries we need installed within it.  How does all of this magic happen?

Are the R & Bioconductor packages somehow build into the `renv` package you created (`2.15.3-1precise1~20140313`)?  If we want to add some new R libraries how would we do that?

Here are the package details for `renv` on a current test instance of the sGMS

```
sudo apt-cache policy renv
renv:
  Installed: 2.15.3-1precise1~20140313
  Candidate: 2.15.3-1precise1~20140313
  Version table:
 *** 2.15.3-1precise1~20140313 0
       1002 file:/opt/gms/4YDBW36/sw/apt-mirror-min-ubuntu-12.04-2015.03.30/mirror/repo.gsc.wustl.edu/ubuntu/ precise-genome-development/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by gatoravi** [comment]
The packages in lucid, [here](https://github.com/genome/genome-snapshot-deps/blob/master/lucid/genome-snapshot-deps-r.depends), that we need in precise currently are,

```
r-tgi-sciclone (>= 1.0.7-2)
r-bioc-cn.mops (= 1.8.9-1)
```

**Comment by gatoravi** [comment]
The goal here is to have a separate repo on github for the renv method or document clearly how this works and how to add/remove packages in the future.

**Comment by mcallaway** [comment]
I am making progress on the process for building the "renv" package, which will contain R 2.15.3 and our list of R packages. I'm noting a discrepancy in the list we have in genome-snapshot-deps-r.depends and the list I have in the "renv" package. I'm going to assume the r.depends list is more correct, update renv, and show you the results to see if we can come to agreement on what _should_ be in our R environment.

Note that my "renv" package is built from a fresh virtual machine, provisioned with puppet. When I'm done, you'll be able to provision the VM yourself to make updates to the renv package.

I'm making fast progress. Hoping to have something done in a day or so.

**Comment by gatoravi** [comment]
@mcallaway  has some awesome documentation on our internal page - [here](https://confluence.gsc.wustl.edu/pages/viewpage.action?title=Packaging+Omnibus&spaceKey=~mcallawa) The procedure outlined there has to be tested out the next time we add/remove an R package to the SGMS. This resource could be helpful to folks outside TGI as well.

The new version of renv is now installed as expected from the new APT dump added here -https://github.com/genome/gms/commit/1d1d9ec3b0c23a23175d3062eb5e5d6f2313b953,

```
gmsuser@clia1 /opt/gms/IX7TW51/sw/workflow/lib/Workflow/DataSource (gms-pub-2015.02.22)> apt-cache policy renv
renv:
  Installed: 2.15.3-1precise1~20150406
  Candidate: 2.15.3-1precise1~20150406
  Version table:
 *** 2.15.3-1precise1~20150406 0
       1002 file:/opt/gms/IX7TW51/sw/apt-mirror-min-ubuntu-12.04-2015.04.09/mirror/repo.gsc.wustl.edu/ubuntu/ precise-genome-development/main amd64 Packages
        100 /var/lib/dpkg/status
```

Sciclone and CnMops are succesfully installed.
