### ISSUE TITLE
first build fails.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#189]
On clia1, the first build always fails with this error,

```
        2015-04-08 14:10:56-0500 clia1: DBD::SQLite::db prepare failed: no such table: dd_table at /opt/gms/68WPW90/sw/ur/lib/UR/DBI.pm line 730.
    23 2015-04-08 14:10:56-0500 clia1: ERROR: Failed to prepare SQL
    24 2015-04-08 14:10:56-0500 clia1: select dd_table.data_source, dd_table.er_type, dd_table.last_ddl_time, dd_table.last_object_revision, dd_table.owner, dd_table.remarks, dd_table.table§
    25 2015-04-08 14:10:56-0500 clia1: from dd_table
    26 2015-04-08 14:10:56-0500 clia1: where dd_table.data_source = ?
    27 2015-04-08 14:10:56-0500 clia1: and dd_table.table_name = ?
    28 2015-04-08 14:10:56-0500 clia1: order by dd_table.data_source, dd_table.table_name
    29 2015-04-08 14:10:56-0500 clia1: no such table: dd_table
    30 2015-04-08 14:10:56-0500 clia1: 2015/04/08 14:10:56 workflow _stop
```

The subsequent builds succeed by re-creating the meta-db as,

```
    22 2015-04-08 14:10:56-0500 clia1: WARNING: Re-creating /opt/gms/68WPW90/sw/ur/lib/UR/DataSource/Meta.sqlite3 from /opt/gms/68WPW90/sw/ur/lib/UR/DataSource/Meta.sqlite3-dump.
```

This seems to happen only when two builds are launched together for the first time. For example, after a fresh install, running `gmbs model1 model2` results in this error.

**Comment by sakoht** [comment]
What re-created the meta-db?

Did this happen automatically?

**Comment by gatoravi** [comment]
Yeah, this happened automatically on the first build that I launch from the SGMS. All the subsequent builds that I launch run successfully. It does sound really weird but I have some pointers from Tony to help debug.

**Comment by gatoravi** [comment]
I haven't seen this issue re-occur on a fresh install. The Meta-db seems to be setup somehow before the first build starts, it must be one of the `genome` commands in the install that must trigger this. I'm leaving this issue open until we test on AWS.

**Comment by gatoravi** [comment]
This seems to be resolved with the metadata update here - https://github.com/genome/tgi-workflow/commit/fb625147a438f60919d1355744e2a047945e0a78
