### ISSUE TITLE
genome sample create command doesnt exist

### ISSUE THREAD

**Issue by shu2010** [genome/gms#192]
Dear authors,

The run with downsampled demo data on both AWS instance as well as local installation were successful. However,  the command "genome sample create" to add external data doesnt exist on either the community ami SGMS_INSTALL_V3 or locally installed SGMS !!
Any work around this will be greatly appreciated.

Cheers

**Comment by GrubLord** [comment]
This commit seems to resolve your issue:
https://github.com/genome/genome/commit/4a2e39d8cd43d1ff819b35144d1dac7576a97381

However, it is not yet in the "gms-pub" branch, which is used in the install process.

**Comment by gatoravi** [comment]
Hi,
Thanks for the message, that is a little strange. Were you following the tutorial referenced [here](https://github.com/genome/gms/wiki/Beginner's-Guide-to-Data-Import) Could you please post the command and the error that you get when you try to run the command?
Thanks,
Avi

**Comment by shu2010** [comment]
Thanks!!
Error with SGMS_INSTALL_V3:

![screen shot 2015-11-20 at 2 33 47 pm](https://cloud.githubusercontent.com/assets/15934207/11291404/d8b944ec-8f93-11e5-828b-8b8c8a56a1d3.png)

**Comment by gatoravi** [comment]
@GrubLord is right, this commit https://github.com/genome/genome/commit/f3ea92e8f3d7978b4a27954004d3a174db5ade80 from @mkiwala seems to have somehow gotten clobbered while merging branches. Thanks for reporting this. 

I've cherry-picked the commit onto the gms-pub branch. To pull this change into your AWS instance, please try to  `cd /opt/gms/${GMS_ID}/sw/genome` and run `git pull`. Alternatively, the target "update-repos" in the Makefile should do the same thing, so you could run `make update-repos` from the same directory where you ran the install step(the directory that has the Makefile in it). Thanks again for reporting this and do let us know if you run into more issues.
