### ISSUE TITLE
tutorial command for adding sequence reads to the system fails with demo SRA data

### ISSUE THREAD

**Issue by shu2010** [genome/gms#193]
Dear Authors,
This problem was encountered on the AWS instance. 
 /opt/bam> genome instrument-data import basic --description='tumor exome 1' --import-source-name='GEO_SRA' --instrument-data-properties="clusters=72512840,target_region_set_name=$TARGET_SET" --source-files="$INSTRUMENT_DATA_DIRECTORY/SRR925765_1.bam" --library="$CAPTURE_LIBRARY_TUMOR"
2015/11/24 01:15:34 Genome::InstrumentData::Command::Import::Basic: analysis_project: Missing required parameter: --analysis-project.
ERROR: analysis_project: Missing required parameter: --analysis-project.

**Comment by mkiwala** [comment]
It looks like analysis project was made a [required property](https://github.com/genome/genome/blob/gms-pub/lib/perl/Genome/InstrumentData/Command/Import/Basic.pm#L15) for `Genome::InstrumentData::Command::Import::Basic` on the gms-pub branch.

I'm not sure whether some other code that uses imported instrument data is actually expecting the analysis project to be populated there or not.  A first step could be to try moving this input property to the `has_optional_input` section.

**Comment by GrubLord** [comment]
There seems to be something of a rabbit-hole of further changes that need to be made, if that's to work. The analysis project seems to be passed to the Workflow, etc., which also have it as a required parameter.

I'd say the better option would be just to set up a temporary analysis-project, even if you don't especially need to keep track of a "project".

**Comment by shu2010** [comment]
Thanks @mkiwala, the patch seems to have fixed the problem for now..

**Comment by GrubLord** [comment]
Yup, my mistake - it seems to have worked after restarting the terminal session. =)
