### ISSUE TITLE
Issue defining clin-seq with imported data

### ISSUE THREAD

**Issue by shu2010** [genome/gms#196]
Dear authors,

The somatic variant call run with imported HCC1143 data was successful. I would like to utilise the clin-seq workflow to create mutation spectrum, mutation diagrams etc. 
I am encountering the following error
genome model define clin-seq --name='hcc1143-clinseq-new' --processing-profile=ac594e8c10ac420aaf8e6cfa64888e92  --exome-model='hcc1143-somatic-exome-new'
'exome_model', and 'processing_profile' may require verification...
Resolving parameter 'exome_model' from command argument 'hcc1143-somatic-exome-new'... found 1
Resolving parameter 'processing_profile' from command argument 'ac594e8c10ac420aaf8e6cfa64888e92'... found 1
2015/11/30 06:23:16 Genome::Model::Input: Attempt to create Genome::Model::Input with multiple ids without these properties: value_class_name, value_id
ERROR: Attempt to create Genome::Model::Input with multiple ids without these properties: value_class_name, value_id
2015/11/30 06:23:16 Genome::Command: Failed to add bridge for 'cosmic_annotation_db' on Genome::Model::ClinSeq if 'a92fab0e62ce4fc19e9200d763c213c3': method add_cosmic_annotation_db_association returned false at /opt/gms/I92H8165/sw/genome/lib/perl/Genome/Model/Command/Define/BaseMinimal.pm line 272
ERROR: Failed to add bridge for 'cosmic_annotation_db' on Genome::Model::ClinSeq if 'a92fab0e62ce4fc19e9200d763c213c3': method add_cosmic_annotation_db_association returned false at /opt/gms/I92H8165/sw/genome/lib/perl/Genome/Model/Command/Define/BaseMinimal.pm line 272

**Comment by gatoravi** [comment]
Not clear immediately what's causing this. I suspect you might have to use the "--cosmic-annotation-db=" option for the `genome model define` command since the default doesn't seem to be working. You should be able to get the list of valid available cancer-annotation-db's by running `genome db list`

Could you maybe try
`genome model clin-seq advise --allow-imported --individual='common_name=??' --samples='id in [??,??,??,??]` where you replace the ?? with the appropriate ID's for your individual and sample? This command should identify the reference-alignment and somatic-variation models that you have already run and specify the `genome model define clin-seq` command to create a new clin-seq model. 
I'm curious to see how this `genome model define` command differs from the one you tried.
Could you also post the output of `genome db list`?

**Comment by gatoravi** [comment]
Just for reference, the DB's in the SGMS are installed by running the 
`genome model import metadata $PATH_TO_gms/setup/metadata/18177dd5eca44514a47f367d9804e17a.dat`

This command is run automatically when one runs the 
`./setup/prime-system.pl --data=hcc1395_1tenth_percent --sync=tarball`  script.

**Comment by shu2010** [comment]
@gatoravi , here is the debug for the commands. 

> Could you also post the output of genome db list?

Note: The DATABASE_NAME is set to <NULL> for cosmic?

genome db list
ID                                               SOURCE_NAME        DATABASE_NAME             EXTERNAL_VERSION   IMPORT_ITERATION   SOURCE_DIRECTORY       DATA_DIRECTORY

---

cancer-gene-list/human/1.1                       cancer-gene-list   human                     1                  1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/cancer-gene-list/human/1
cosmic/65.1                                      cosmic             <NULL>                    65                 1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/cosmic/65_v1
dbvar/human/build37.1                            dbvar              human                     build37            1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/dbvar/human/build37
genome-db-dbsnp/human/build37/132.1              genome-db-dbsnp    human/build37             132                1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/genome-db-dbsnp/human/build37/132
tgi/cancer-annotation/human/build37-20131010.1   tgi                cancer-annotation/human   build37-20131010   1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/tgi/cancer-annotation/human/build37-20131010
tgi/misc-annotation/human/build37-20130113.1     tgi                misc-annotation/human     build37-20130113   1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/tgi/misc-annotation/human/build37-20130113
ucsc/human/build37.1                             ucsc               human                     build37            1                  /opt/gms/I92H8165/db   /opt/gms/I92H8165/db/ucsc/human/build37

> Could you maybe try
> genome model clin-seq advise --allow-imported --individual='common_name=??' --samples='id in [??,??,??,??]

genome model clin-seq advise --allow-imported --individual='common_name=HCC1143' --samples='id in [39c3ae15f59542a9bb30ee0c2a516c62,47c7d128b7354bc8ba3419a3ffe98853]'
Resolving parameter 'samples' from command argument 'id in [39c3ae15f59542a9bb30ee0c2a516c62,47c7d128b7354bc8ba3419a3ffe98853]'... found 2
Resolving parameter 'individual' from command argument 'common_name=HCC1143'... found 1

EXAMINE INDIVIDUAL
id  name    common_name species_name    upn gender  ethnicity   race
f336469d94ff43f5b708a5a9b6da1e8d    HCC1143 HCC1143 human   HCC1143 female  NULL    NULL

EXAMINE DESIRED PROCESSING PROFILES
reference-alignment: Nov 2011 Default Reference Alignment <2635769>
wgs somatic-variation: Oct 2012 Default Somatic Variation WGS <2762562>
exome somatic-variation: Oct 2012 Default Somatic Variation Exome <2762563>
rna-seq: October 2012 Default Ovation V2 RNA-seq <2762841>
ERROR: Can't call method "name" on an undefined value at /opt/gms/I92H8165/sw/genome/lib/perl/Genome/Model/ClinSeq/Command/Advise.pm line 542.

>  "--cosmic-annotation-db=" option for the genome model define command 

genome model define clin-seq --name='hcc1143-clinseq-new' --processing-profile=ac594e8c10ac420aaf8e6cfa64888e92 --cancer-annotation-db='tgi/cancer-annotation/human/build37-20131010.1' --cosmic-annotation-db='cosmic/65.1' --exome-model='hcc1143-somatic-exome-new'

This worked!!

Thanks
Shu

**Comment by gatoravi** [comment]
Great. Yeah that explains it, the defaults in this file https://github.com/genome/genome/blob/gms-pub/lib/perl/Genome/Model/ClinSeq.pm seem to have been updated in the gms-pub branch by mistake. I've pushed a commit fixing this here - https://github.com/genome/genome/commit/a6614cf3e51f3239fd8dbc34d3c58a6fb186d970

Could you try the 

```
genome model clin-seq advise --allow-imported --individual='common_name=HCC1143' --samples='id in [39c3ae15f59542a9bb30ee0c2a516c62,47c7d128b7354bc8ba3419a3ffe98853]'
```

after running a `git pull` from within the genome repository(this should be in `/opt/gms/${GMS_ID}/sw/genome`) ?

**Comment by shu2010** [comment]
here you go:

 git pull
remote: Counting objects: 629, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 629 (delta 386), reused 379 (delta 379), pack-reused 229
Receiving objects: 100% (629/629), 175.23 KiB | 125 KiB/s, done.
Resolving deltas: 100% (430/430), completed with 80 local objects.
From http://github.com/genome/genome
   abecb59..a6614cf  gms-pub    -> origin/gms-pub
   35eb46a..7818afb  cle-snapshot -> origin/cle-snapshot
   a9a1595..80f3a61  master     -> origin/master
   a9a1595..97cd34f  model-tests -> origin/model-tests
   a9a1595..97cd34f  perl-tests -> origin/perl-tests
   b84478a..97cd34f  snapshot   -> origin/snapshot
- [new tag]         genome-3661 -> genome-3661
- [new tag]         genome-3663 -> genome-3663
  From http://github.com/genome/genome
- [new tag]         genome-3662 -> genome-3662
- [new tag]         genome-3664 -> genome-3664
  Updating abecb59..a6614cf
  Fast-forward
  lib/perl/Genome/Model/ClinSeq.pm |    4 ++--
  1 file changed, 2 insertions(+), 2 deletions(-)

genome model clin-seq advise --allow-imported --individual='common_name=HCC1143' --samples='id in [39c3ae15f59542a9bb30ee0c2a516c62,47c7d128b7354bc8ba3419a3ffe98853]'

Resolving parameter 'samples' from command argument 'id in [39c3ae15f59542a9bb30ee0c2a516c62,47c7d128b7354bc8ba3419a3ffe98853]'... found 2
Resolving parameter 'individual' from command argument 'common_name=HCC1143'... found 1

EXAMINE INDIVIDUAL
id  name    common_name species_name    upn gender  ethnicity   race
f336469d94ff43f5b708a5a9b6da1e8d    HCC1143 HCC1143 human   HCC1143 female  NULL    NULL

EXAMINE DESIRED PROCESSING PROFILES
reference-alignment: Nov 2011 Default Reference Alignment <2635769>
wgs somatic-variation: Oct 2012 Default Somatic Variation WGS <2762562>
exome somatic-variation: Oct 2012 Default Somatic Variation Exome <2762563>
rna-seq: October 2012 Default Ovation V2 RNA-seq <2762841>
ERROR: Can't call method "name" on an undefined value at /opt/gms/I92H8165/sw/genome/lib/perl/Genome/Model/ClinSeq/Command/Advise.pm line 542.
