### ISSUE TITLE
Does output from 'genome sys gateway list' in the VM make sense? 

### ISSUE THREAD

**Issue by malachig** [genome/gms#20]
The documentation for the gms installation says that:
### You should see two gateways, one for your new home system and one for "GMS1"

When I fire up a fresh install in a VM I see this:

GMS1     genome.wustl.edu                          <NULL>        <NULL>         initial GMS at TGI   pub/software/gms/testdata/GMS1                                                /opt/gms/GMS1
SWR360   blade16-4-16.gsc.wustl.edu                <NULL>        <NULL>         SWR360                                                blade16-4-16.gsc.wustl.edu:/opt/gms/SWR360   /opt/gms/SWR360

Two questions.  Should SWR360 be attached by default like this?  Should I see one for my 'home system' as the comment in the docs indicates?

**Comment by sakoht** [comment]
It was never implemented.  It should be there for completeness but won't break anything.

That SWR one should be renamed example, and the installer should copy it, and do findreplace with its own name.

**Comment by malachig** [comment]
I find the current flow a bit confusing from a user perspective.  When I finish the install, the tutorial suggests that I run genome sys gateway list.  I'm told that I should see two gateways, one for my home system (not actually seen) and one for GMS1.  I did see GMS1, but later in the tutorial I'm told to attach it again.  But its already attached...  I had to actually detach it and attach it with the FTP method to do the sync.

Also, do we really need the SWR example in here that indicates a base_dir the user can not actually list?  

I think having an entry for the home system would be nice and nothing else to start.  Then later in the tutorial the user can attach GMS1, then we ask the user to list the gateways and now there are two.  I think that would be more clear to the user.

**Comment by sakoht** [comment]
There is either:
1. A bug in is_attached 
2. Something pre-attaching GMS1

Probably the former?

And no the SWR thing was only leg there as an example to make the template for the local/novel file.

**Comment by malachig** [comment]
I think this issue really just comes down to better explaining to the user what is meant by the output of 'genome sys gateway list'. The SWR360 entry is only entered as an example.  It is not attached by default.

I'm not sure if having this example is really that helpful.  How does the SWR360 example wind up in there in the first place? During import of metadata?  Some other point?

**Comment by ghost** [comment]
I don't see SWR360 in the .dat file.

**Comment by malachig** [comment]
It looks like the output from 'genome sys gateway list' is generated by querying the contents of /opt/gms/$SYS_ID/known-systems/ in a standalone GMS installation.  These files are placed their during the install from templates here:
https://github.com/genome/gms/tree/ubuntu-12.04/setup/gms-home-skel/known-systems/

That dir contains two files: 'GMS1.tsv' and 'SWR360.tsv'.

We should add a step in the Makefile to customize that second file.  First we should rename it to 'LocalSystem.tsv' or the like.  Then during the installation it should be renamed '$SYS_ID.tsv' before being placed in /opt/gms/$SYS_ID/known-systems/.  The contents of the file should be transformed as follows from:

```
blade16-4-16.gsc.wustl.edu  somekeySWR360   SWR360          blade16-4-16.gsc.wustl.edu:/opt/gms/SWR360  blade16-4-16.gsc.wustl.edu:/opt/gms/SWR360
```

to:

```
$hostname   somekey$SYS_ID  $SYS_ID         $hostname:/opt/gms/$SYS_ID  $hostname:/opt/gms/$SYS_ID
```

Or something similar to make the output of 'genome sys gateway list' at bit more clear.  For example, if I do this manually in a test system I get output that looks like this:

```
ID        HOSTNAME           IS_CURRENT   IS_ATTACHED   ATTACHED_VIA   DESC                 FTP_DETAIL                       NFS_DETAIL                   BASE_DIR
--        --------           ----------   -----------   ------------   ----                 ----------                       ----------                   --------
GMS1      genome.wustl.edu                1             rsync          initial GMS at TGI   pub/software/gms/testdata/GMS1                                /opt/gms/GMS1
N5IQ908   precise64          1            1             local          N5IQ908                                               precise64:/opt/gms/N5IQ908   /opt/gms/N5IQ908
```

That looks much nicer and is more consistent with what is described in the tutorial documentation.

**Comment by gatoravi** [comment]
This has been done here, https://github.com/genome/gms/commit/3c5d40af274af8d5e409be62d99223ac5f1ff1f8

**Comment by malachig** [comment]
This looks good now.  The output the user sees from a test of 'genome sys gateway list' during the tutorial should now be more intuitive.  Closing this issue.
