### ISSUE TITLE
Finalize provisioning of GMS virtual machine environment

### ISSUE THREAD

**Issue by malachig** [genome/gms#21]
We want the following ultimate setup:
4 disks total:  
- 1 VMDK for the OS,  '/' mounted on a partition 'sda1' of 'sda' device within the VM.  Vagrant does this for us when we fire up Ubuntu precise. This disk is 80Gb in size and can not be changed easily
- 1 VDI for temp space, '/tmp' mounted on a partition 'sdb1' of 'sdb' device within the VM.  This disk will be configurable in size, 2Gb by default and can be placed any location the user desires by modifying the vagrant file.  Because this is '/tmp' special consideration will have to be given to user permissions in the make process.
- 1 VDI for the GMS install, '/opt/gms' mounted on a partition 'sdc1' of 'sdc' device within the VM.  This disk will be configurable in size, 2Gb by default and can be placed any location the user desires by modifying the vagrant file.
- 1 VDI for the GMS data, '/opt/gms/$GENOME_SYS_ID' mounted on a partition 'sdd1' of 'sdd' device within the VM.  This disk will be configurable in size, 2Gb by default and can be placed any location the user desires by modifying the vagrant file.  Since this relies on a unique GMS ID created during the Make process, mounting this volume will require special consideration in the Makefile.

All of this will configured by a combination of entries in 'Makefile', 'Vagrantfile.standalone.virtualbox', and 'drive_setup.sh'

Do as much as possible during the provisioning step of firing up the virtual machine.  Where necessary make custom entries in the Makefile.

**Comment by malachig** [comment]
I think this is all working...  Within the VM, after installing a local copy of GMS1 (including the TST1 test data) my disk usage looks like this:

/dev/mapper/precise64-root                                         79G  6.2G   69G   9% /
/dev/sda1                                                         228M   25M  192M  12% /boot
/dev/sdb1                                                         2.0T   31G  1.9T   2% /tmp
/dev/sdc1                                                         2.0T  414G  1.5T  22% /opt/gms
/vagrant                                                          931G  395G  537G  43% /vagrant
/dev/sdc1                                                         2.0T  414G  1.5T  22% /opt/gms/REB9561

What I'm not total clear about at this stage is why /vagrant reports disk usage the way it does...  Still a pass through to the host OS?  In which case it is reporting total disk usage by the host system on that volume.  Within the VM, /vagrant only contains 3.2G of files.  These are the install files presumably.

**Comment by malachig** [comment]
Genome commands are writing their /tmp files here without issue.  I'm running a Ref align build right now and temp objects are being created there for .sai files, etc.  I'm hopeful that this will improve overall performance of genome analysis in the VM because now the virtual OS is writing its files to one volume, the input data and final results are going to a second volume, and all /tmp writing is happening on a third volume.

Overall, the provisioning seems to be successful.  However, we still need to confirm that when a job requests a large amount of /tmp space (e.g. an RNA-seq build) that openlava will correctly identify /tmp within the VM as having enough space to fill this resource request.

I should be able to confirm that soon.

**Comment by obigriffith** [comment]
It seems like some of the stuff that has been added for setting up drives within vagrant are being inappropriately applied to non-vagrant install.

#Now that $(GMS_HOME) exists, it should be mounted
#sudo echo /dev/sdd1  $(GMS_HOME)  ext4  defaults  0  0 >> /etc/fstab
sudo bash -c 'echo /dev/sdd1  $(GMS_HOME)  ext4  defaults  0  0 >> /etc/fstab'
sudo mount | grep -q "^/dev/sdd1" || sudo mount -t ext4 /dev/sdc1 $(GMS_HOME)

**Comment by malachig** [comment]
I think the issue Obi describes above has been fixed but Avi is going to confirm by testing on blade16-4-16.

I have confirmed that within the VM install, the mounting of /tmp to a separate volume is now working.  This was originally blocking me from launching an RNA-seq build, but I just launched a job that requests ~150 Gb of /tmp space and lsf correctly detected that /tmp is big enough to accommodate this now.  Temp files needed by tophat are being written to /tmp as expected and without issues.

**Comment by gatoravi** [comment]
So i haven't been able to push the small change to the Makefile, but the install went all the way through on the Blade. I haven't downloaded the test data yet. 'bhosts' and 'bjobs' fail but genome disk group list ,
'genome disk volume list' and 'genome sys gateway list'  all seem to work. The bash environment variables are set automatically, looks like the issue we had earlier seems to disappear after re-imaging the blade.
![gms_blade1](https://f.cloud.github.com/assets/764948/1403780/e8f6ea84-3cf8-11e3-8675-8aa603e34ae7.png)

**Comment by malachig** [comment]
The provisioning has been reworked yet again.  We tried using symlinks from ~/git/gms/ to VDI images that were moved elsewhere.  This does not seem to work very well.  The symlinks seemed to prevent the VM from actually writing data to the VDIs even though on the surface everything seemed fine.  All data was being written to the main virtual box VDI in way that was confusingly hidden from host (except that disk was being consumed by apparently hidden files)...

It also seems you have to be careful when performing a vagrant halt and vagrant up to make sure that provisioning is not repeated.  You can do this several ways.  
- After the VM is setup you can comment out the provisioning step in the Vagrantfile before doing 'vagrant up' again
- You can do 'vagrant up --no-provision

We may also be able to change the provisioning script itself to check whether provisioning is already done...

**Comment by malachig** [comment]
Considerable additional checks were added to the provisioning scripts (some of which are described in issue #26).

**Comment by malachig** [comment]
We haven't had any issues with disk provisioning in the virtual machine environment for a while.  We still need to document the process for allowing raw disk access (instead of VDIs) for performance reasons but for now I am closing this issue.
