### ISSUE TITLE
Rename TST1 models to use the nice clean, intuitive names used in the tutorial

### ISSUE THREAD

**Issue by malachig** [genome/gms#22]
The TST1 model names are imported from TGI's GMS starting with a clin-seq model and tracing backwards to all the underlying models.  This is great.  Once in the tutorial environment, the auto-generated names from TGI are not easy for the uninitiated to follow.  

Purely for the purposes of the tutorial, we should rename these models to have simpler, cleaner names.  The ones already indicated in the tutorial are fine.

A simple fix could actually be to have a step in the tutorial that renames the models after they are imported.  This could be triggered by the import step, or a separate script that is run that does random tidying like this to help the user...

**Comment by sakoht** [comment]
After renaming,a fresh 
genome model export metadata 

Should remake the file.

What is on the FTP site should be replaced.

**Comment by malachig** [comment]
Ok, that is probably the more robust solution.

Some follow up questions...  I have documented what I think are answers in some cases.  Please comment when you get a chance.

1.) Is this totally independent from grabbing the filesystem data that goes along with models or is that part of this export command also?  From the 'genome model export metadata' code it looks like disk allocations are indeed being identified.  How does this relate to the generation of the ~350Gb of actual files needed to run the TST1 analysis?  I'm under the impression that some manual patching of that payload has occurred (for example as described in issue: #15 ).  If we repeat the dump of metadata, would any of that need to be redone?

2.) Which model ID is the one we are actually exporting from TGI GMS to be imported into Standalone GMS?  This is a clin-seq model for TST1 right?  Got the ID handy?  From within the standalone GMS I see that the following clin-seq model has been imported: 2891454740.  Correct? 
Answer: I believe 2891454740 is correct.

3.) Should the '--refdata' option of 'genome model export metadata' be used?
Answer: No, we want everything not just the reference data

4.) Once a new metadata file is created.  Where does it go?  I see that the current metadata object lives here: http://genome.wustl.edu/pub/software/gms/testdata/GMS1/export/2891454740-2013.09.11.dat

How does one stage something there?  I'm guessing copy it to here and wait for syncing to occur:
/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/export/

Correct?  Answer: I  believe this is all correct.

**Comment by malachig** [comment]
Still waiting for input from Scott on all of the above, but as a first step I have cleaned up the model names used in the tutorial and I have renamed the corresponding models on the TGI side to have the correct names.  The next step would be to redo the metadata dumping from TGI, creating a new metadata file, staging that on the FTP, updating the import command in the tutorial, testing it in a standalone install and make sure everything is still working.

**Comment by sakoht** [comment]
1) Independence from FS data: The file of data to import sits on the GMS1 disk.  It also happens to be the data we use to test the importer/exporter, so a duplicate is in the source tree.  But is probably uglier for the user.
2) Yes.  That's the model I was using.  Its ID is in the file name.
3) Correct/No.  That would let us dump a smaller (GMS0?) data set providing references and annotation.

**Comment by sakoht** [comment]
It looks like the rename is already done?

**Comment by malachig** [comment]
Yes, I did the rename on the TGI side and I attempted a dump of the new metadata.  I had then placed this in the FTP staging dir and was waiting for it to actually stage.  It sounds like since then it needed to get updated again...

**Comment by sakoht** [comment]
Just because there were dump code changes (metrics!).

**Comment by malachig** [comment]
I think this is resolved now.  The models have been renamed and the metadata dump file has been updated and the import tested.
