### ISSUE TITLE
persistent permissions issue

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#24]
# set permissions for GMS_HOME

The first time I get to the below step I have permissions problem. It seems like I am expected to be in genome group before that has actually been set.

echo GMS_HOME is /opt/gms/2JDB553
GMS_HOME is /opt/gms/2JDB553
sudo chown genome:genome /opt/gms/2JDB553
sudo chmod g+rwxs /opt/gms/2JDB553
# install a directory skeleton

cp -a setup/gms-home-skel/\* /opt/gms/2JDB553
cp: cannot create directory `/opt/gms/2JDB553/db': Permission denied
cp: cannot create directory`/opt/gms/2JDB553/export': Permission denied
cp: cannot create directory `/opt/gms/2JDB553/fs': Permission denied
cp: cannot create directory`/opt/gms/2JDB553/known-systems': Permission denied
cp: cannot create directory `/opt/gms/2JDB553/sw': Permission denied
cp: cannot create directory`/opt/gms/2JDB553/tmp': Permission denied
cp: cannot create directory `/opt/gms/2JDB553/var': Permission denied
make[1]: *** [done-host/gms-home] Error 1
make[1]: Leaving directory`/home/ogriffit/gms'
make: **\* [all] Error 2

**Comment by obigriffith** [comment]
Alternatively, this may just require a complete log out and log back in. But, this is not intuitive. 
Can we do something like discussed here:
http://arkaitzj.wordpress.com/2010/03/08/linux-add-user-to-a-group-without-logout/
or
http://blog.edwards-research.com/2010/10/linux-refresh-group-membership-without-logging-out/
or
http://serverfault.com/questions/74934/refresh-supplementary-group-memberships-without-logging-in-again/75151#75151

**Comment by obigriffith** [comment]
I guess the question is whether the make will continue after the above interventions

**Comment by gatoravi** [comment]
yes, issue36 is related to this, using Obi's workaround helps me get past this error. Something is not right with the permission, only root seems to be able to write to /opt/gms/SYSID and not the default user who installs the GMS on a standalone box.

**Comment by obigriffith** [comment]
This might be something that is fixed with a reboot?  Something to do 
with a new groups assignment not taking immediate effect?

**Comment by malachig** [comment]
I believe that remembering to logout and login again combined with additional fixes to the Make process have resolved this issue.  I have made the warnings about logging out more prominent in the installation process.  Closing for now.
