### ISSUE TITLE
 special device /dev/sdc1 does not exist

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#25]
Tried to install gms on blade16-4-16 directly, it has Ubuntu12.04.3.
make gives this error,
# 
# all:
# Install the GMS on the local Ubuntu 12.04 (Precise) host...
# 

sudo -v
make home
make[1]: Entering directory `/home/aramu/Sandbox/gms'
# 
# done-host/user-home-root:
# copying configuration into the current user's home directory
# re-run "make home" for any new user...
# 
# [ `basename /root` = `basename done-host/user-home-root | sed s/user-home-//` ]

cp /home/aramu/Sandbox/gms/setup/home/.??\* ~root
touch done-host/user-home-root
# 
# home:
# 
# add the current user to the correct groups

sudo usermod -aG genome,sudo,fuse root || true # wait for groups to be defined
make[1]: Leaving directory `/home/aramu/Sandbox/gms'
DEBIAN_FRONTEND=noninteractive make setup
make[1]: Entering directory`/home/aramu/Sandbox/gms'
# 
# s3fs:
# 

[ `which s3fs` ] || make done-host/s3fs-install
# 
# done-host/gms-home: (recurses into done-host/gms-home-{raw,vm})
# 

sudo -v
# the creation of /opt/gms varies depending on whether this is a VM or not
# on a VM we want all disk activity to "pass through" to the host to be shared across installs

([ -e /vagrant ] && make done-host/gms-home-vm) || true
[ -e /vagrant ] || make done-host/gms-home-raw
make[2]: Entering directory `/home/aramu/Sandbox/gms'
make[2]:`done-host/gms-home-raw' is up to date.
make[2]: Leaving directory `/home/aramu/Sandbox/gms'
# set permissions on the root directory above the GMS home so that additional systems can attach

sudo touch /opt/gms/test
sudo chown genome:genome /opt/gms /opt/gms/.\* /opt/gms/*
sudo chmod g+rwxs /opt/gms /opt/gms/.\* /opt/gms/*
# make the home for this GMS

[ -d "/opt/gms/B5H3440" ] || sudo mkdir -p /opt/gms/B5H3440
# Now that /opt/gms/B5H3440 exists, it should be mounted
# sudo echo /dev/sdd1  /opt/gms/B5H3440  ext4  defaults  0  0 >> /etc/fstab

sudo bash -c 'echo /dev/sdd1  /opt/gms/B5H3440  ext4  defaults  0  0 >> /etc/fstab'
sudo mount | grep -q "^/dev/sdd1" || sudo mount -t ext4 /dev/sdc1 /opt/gms/B5H3440
mount: special device /dev/sdc1 does not exist
make[1]: **\* [done-host/gms-home] Error 32
make[1]: Leaving directory `/home/aramu/Sandbox/gms'
make: **\* [all] Error 2

**Comment by malachig** [comment]
This is related to issue #21 

We need to put these two statements into conditional logic so that they only happen if the user is doing the virtual machine install:

sudo bash -c 'echo /dev/sdd1 /opt/gms/B5H3440 ext4 defaults 0 0 >> /etc/fstab'
sudo mount | grep -q "^/dev/sdd1" || sudo mount -t ext4 /dev/sdc1 /opt/gms/B5H3440

I'm not sure of the best way to do that.  It looks like [ -e /vagrant ] is being used for this purpose...

**Comment by sakoht** [comment]
I have at times used:

[ -e /vagrant ] && make vm-disks

Then a make target like "vm-disks" can have its own branch of work.  A little easier than putting the test on each line.

**Comment by malachig** [comment]
Yeah, that makes sense.  

As long as it is triggered at that point because it can't happen until /opt/gms/$GSM_ID is actually created, which happens right there.  Right now it would just have those two lines but maybe it is cleaner to have this in its own make target anyway.

**Comment by malachig** [comment]
I added this, committed and pushed.  Think it is working now.  Avi, can you try a fresh install and make sure it works in the non-VM install?

**Comment by gatoravi** [comment]
I'm unable to push to the repo, I think I need to be added as a
contributor, there has to be a "|| true" added to the conditional logic I
think, otherwise it exits with an error. I'm trying to install now on the
blade, I've been having ssh problems accessing the linus machines since
last night.
