### ISSUE TITLE
With the current VM disk provisioning strategy, the user can clobber their system by accident

### ISSUE THREAD

**Issue by malachig** [genome/gms#26]
The current provisioning arrangement seems to be working smoothly.  However, there is an issue with the way the user interacts with the VM from the host.

When 'make vminit' completes, 'vagrant up' has completed, the VM has booted and the user logs in by 'vagrant ssh'.  The user then runs 'make' to complete the install and /opt/gms/$GMS_ID is created and mounted to a sdd1.

All is well.  The user can log out and log back in with vagrant ssh and everything is maintained.  However, if the user wants to reboot the host system or turn off the VM to prevent resource usage they have to be careful which vagrant commands they execute to do so.
- 'vagrant destroy' will clean up everything and obviously destroys the VM.  This is fairly obvious to the user.
- 'vagrant reload' successfully reboots the system, but once loaded /opt/gms/$GMS_ID has been clobbered.
- 'vagrant halt' shuts down the system.  Then if the user tries 'vagrant up', vagrant attempts to reattach the VDI images.  This causes an error and the user must comment out these lines in the vagrantfile to proceed.  Having done so, 'vagrant up' will work but upon booting once again /opt/gms/$GMS_ID has been clobbered.

It seems that the only safe way to shutdown and reload the VM is to use:
- 'vagrant suspend' and 'vagrant resume'

This problem could possibly be solved by removing all creation of VDI images and all provisioning from the hands of the vagrant file.  It could instead be done in the Makefile by executing VBoxManage commands.  Specifically the following steps could be attempted in the makefile:
- use VBoxManage createhd to create the three VDI disks
- use VBoxManage storageattach to attach them to sdb, sdc, and sdd
- perform all partitioning, formatting and mounting commands in the Makefile
- remove the above steps and the provisioning step from the Vagrantfile.  At that point 'drive_setup.sh' would no longer be needed.

**Comment by sakoht** [comment]
The setup/vmdisk.sh is run by the Vagrantfile, and only creates VDI disk files if required.

**Comment by malachig** [comment]
This is working much better.  But I just encountered the following situation.  Did a VM install.  Created symlinks.  Then I at some point I had to do a vagrant up.  Seemed like new VDI disks were created and clobbered my symlinks somehow.  If the virtual disks are there, they do not get recreated but if instead these are symlinks they will be.  That seems surprising.  Not exactly sure what happened there.  In the end I wound up with part of the install written to the disks I had moved elsewhere and part in the second set of disks created in the default location...

Perhaps the check for existence of VDI disks should check for symlinks explicitly?

**Comment by malachig** [comment]
Never mind, think I figured out what happened here.  Testing now.

**Comment by malachig** [comment]
Somehow I still wound up with clobbered VDI files in my latest installation.  I made it all the way through to syncing GMS1 data over.  Installation went smoothly.  I had to reboot my host so I did a 'vagrant halt'.  When the host system was rebooted I did a 'vagrant up'.  When I logged in, /opt/gms and /opt/gms/$sys_id were completely empty.

Perhaps have a nested mount: (sdc1 -> /opt/gms) and (sdd1 -> /opt/gms/$sys_id) is causing a problem.

Several changes will be required to test this theory.  Perhaps it would be simpler to simply have one data mount (sdc1 -> /opt/gms) and one temp mount (sdb -> /tmp).  In order to test this, we will have to comment out lines in drive_setup.sh, the vagrant file, move_disk_locations.sh, the makefile and possible elsewhere.

I am testing this now.  I commented out all lines related to mounting (sdd1 -> /opt/gms/$sys_id)

**Comment by malachig** [comment]
This seems to be working better now.  If you want to be extra careful when rebooting the VM you can take the following steps:
- Comment out the provisioning step in the Vagrantfile after the VM is setup
- Only use 'vagrant suspend' when you need to reboot the host system, and use 'vagrant resume' to start it again
- If you do need to hard reboot the VM, you can also use 'vagrant halt' and 'vagrant up --no-provision'
