### ISSUE TITLE
bjobs and bhosts failing on ubuntu install

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#29]
After make finishes install, bjobs and bhosts fail to work as expected, the message on the screen is.. 
LSF daemon (LIM) not responding ... still trying

**Comment by gatoravi** [comment]
when 'lim' is run in DEBUG mode, this is the error that I get. 
"setMyClusterName: Local host blade16-4-16 not defined in cluster file /opt/openlava-2.0/etc/lsf.cluster.openlava"

The 'lsf.cluster.openlava' has the host name as 'blade16-4-16.gsc.wustl.edu' . When I edit it manually to 'blade16-4-16' and restart openlava, bjobs and bhost work fine !

So the host name that is set by a perl script in the Makefile    

'cat setup/openlava-config/lsf.cluster.openlava | setup/bin/findreplace-gms >  /tmp/lsf.cluster.openlava' 

needs to be modified ? I'm not sure why the full host-name does not work.

**Comment by sakoht** [comment]
Can you ping with a fully qualified hostname?  

It may not know it is on the .gsc:wustl.edu domain.

**Comment by gatoravi** [comment]
ping works on the full hostname !

**Comment by sakoht** [comment]
I guess the makefile just needs to trim down to the abbreviated hostname?

BTW: Niel Das in LIMS is working on using OpenLava for their work on the CLIA stuff.  They are probably already ahead of where this stuff is on setting up configuration.  Picking his brain may be good.

**Comment by gatoravi** [comment]
Thats a good idea, im wondering if this is just an issue with the blade or
with all standalone installs. Ill check with Neal about this. Im gonna go
ahead with the install from here and see if i can make any builds with this
setup.

**Comment by indraniel** [comment]
Shin Leong, also in LIMS, will also know about the CLIA OpenLava setup
details.  He has setup & tested out a master/slave configuration on 2
OpenStack VMs.

Cheers,
Niel

**Comment by gatoravi** [comment]
The resolv.conf file has 'domain gsc.wustl.edu'  and after the install the lsf.cluster.openlava file has host-name is 'bladle16-4-16.gsc.wustl.edu' . When it is changed to just 'blade16-4-16', the install goes through. 
Shin and I suspect that open lava might be confused because it is appending 'gsc.wustl.edu' twice to the host-name. A simple fix to this would be to parse out the hostname in the perl script, but is this a problem only on this domain(WUSTL) or will other users have this problem as well ?

**Comment by malachig** [comment]
We were able to get the install to work including bjobs and bhosts on a machine on a home network.  Did not have this problem there.  That is one data point.  I say we try a fix along the lines you suggest and see how it goes for now.

**Comment by gatoravi** [comment]
fixed and pushed. bobs works ok now on the blade !
