### ISSUE TITLE
Cut the pipelines from table 1 that are not behind MedSeq into a different section.

### ISSUE THREAD

**Issue by sakoht** [genome/gms#3]

**Comment by malachig** [comment]
Or maybe we should drop them entirely...  If we are not ready support them and indeed have not tested them yet, perhaps they should not be mentioned in the paper at all.  Currently we support the following: 
Genotype-microarray, reference-alignment, somatic-variation, rna-seq, differential-expression, and med-seq.

But we also list additional pipelines such as de-novo-assembly, somatic-validation, small-rna, etc.

Options:
1.) Leave the table the way it is.  With supported pipelines in bold and additional untested pipelines in regular font.
2.) Remove them and only mention stuff we actually support
3.) Create a separate table in the supplementary materials
4.) Document them somewhere else entirely.  GMS wiki perhaps

**Comment by malachig** [comment]
This is done.  Went with option (2).  Although we should also do option (4) in the future as we improve the wiki.  Closing this issue now.

**Comment by sakoht** [comment]
Good call.
