### ISSUE TITLE
Site specific disk group names are causing a failure during 'setup/prime-allocations.pl'

### ISSUE THREAD

**Issue by malachig** [genome/gms#34]
It looks like someone at TGI (mburnett) recently added some logic to Genome::Disk::Group.pm that requires creation to disk groups to use a defined set of names.  In the standalone GMS we are using a disk group 'reads' that is not in the approved list below:

<pre>
# TODO This needs to be removed, site-specific
my %VALID_NAMES = (
    info_apipe => 1,
    info_apipe_ref => 1,
    info_alignments => 1,
    info_genome_models => 1,
    research => 1,
    systems_benchmarking => 1,
);
</pre>

Preferred resolution to this issue is not known at this time...  Adding 'reads' to the list above within a VM installation does work...  We don't want the user to have to make this kind of code modification every time they do an install though...

**Comment by sakoht** [comment]
If you make the change only on the pub branch it will endure subsequent merges ...unless/until master edits the list again.

**Comment by malachig** [comment]
Ok, this is what I wound up doing

**Comment by malachig** [comment]
This seems to be working now.
