### ISSUE TITLE
When I log into test box blade16-4-16 '/etc/genome.conf' is not sourced

### ISSUE THREAD

**Issue by malachig** [genome/gms#40]
How is '/etc/genome.conf' sourced?  

It looks like the source command lives in this file in the repo 'setup/home/.bash_aliases'.  Then during the make process, 'done-host/user-home-%: ' attempts to copy this file and others into the home dir of the user doing the installation as follows:

cp $(PWD)/setup/home/.??\* ~$(USER)

It looks like on this test machine 'blade16-4-16', $USER was 'root' at this point this was run.  The config files from setup/home/ therefore wound up in /root.  Later when we login to this box as 'ssmith' the home configuration is not setup properly.

Avi, didn't you run make as 'ssmith'?

In theory we should be able to fix this by doing the following when logged in as ssmith:
make home

It would be good to understand why this happened and how we can avoid it in the future...

**Comment by malachig** [comment]
I ran, 'make home'.  Since the original make process was apparently run with sudo (perhaps it wouldn't work otherwise) I had to use 'sudo make home' here.  Now all the config files are in the user's home dir and when I log out and back in again, /etc/genome.conf is correctly sourced.

How can we avoid this situation in the future?  Either the user needs to be reminded to do this, or even better, the make process should handle this situation without user interaction.

**Comment by gatoravi** [comment]
While running make I encountered bunch of permission denied'd and the make process would exit. Hence I ran 
'sudo make' and this helped to run the process all the way through. This could explain some of the weird permissions issues that I've been having. #39

**Comment by malachig** [comment]
Yes, that makes sense now.  

You should not run 'sudo make'.  If there are commands that require sudo during the make, we should make those individual steps use 'sudo'.

We should also consider adding a line to the beginning of the make process to ensure that the user is not already root and abort if so.

**Comment by malachig** [comment]
I tried a fresh installation on CLIA1.  That box seems to have very restrictive permissions when I log in.  My home directory did not even exist and had to be created by root.  Running the make there resulted in several places where sudo was required to continue.  I have committed these here: d6692d029eb7d83ac67d2cc76687d5638dd312f4

I will now test to make sure none of this causes problems with the VM installation.

**Comment by malachig** [comment]
This issue appears to be resolved.  All steps in the make process now complete without error.  If the user ignores the installation instructions and does 'sudo make' instead of 'make' it may still cause problems downstream...  We could add a note about this in the installation documents but they are already pretty verbose.  We'll leave this as is for now and revisit if necessary.
