### ISSUE TITLE
Error in reference alignment (bam-errorrate version0.9 is not valid tool)

### ISSUE THREAD

**Issue by malachig** [genome/gms#41]
I noticed this error on the test box blade16-4-16.

ERROR: bam-errorrate version0.9 is not valid tool at /opt/gms/YBPD617/sw/genome/lib/perl/Genome/Model/Tools/BioSamtools/ErrorRate.pm line 62.

This will need to be fixed before reference alignment will work.  

Several things will have to be changed to get past this error:
- Our applications archive is missing two versions of bam-errorrate (0.6 is installed but 0.7 and 0.9 are not).
- Until this tool is packaged properly and the genome code is changed to look for a proper installation, we should at least bring these two versions into the fold.
- Currently they are installed here within TGI: /gscuser/iferguso/bin/
- We could install them where the previous version is until we get packaging sorted out: /gsc/pkg/bio/bam-errorrate/.  In order to do this we will have to login to 'deploy' within the TGI
- Then we need to update the gms master branch to use these new paths
- Then we need to update the gms pub branch to use paths with the base: $ENV{GENOME_SW}
- Then we would need to create an updated archive of the apps package that includes these and stage it to the FTP site.
- Current version lives here on the staging server: /gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/setup/archive-files/apps-2013-10-01.tgz
- Created this new version with the new files: /gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/setup/archive-files/apps-2013-11-20.tgz
- Wait until this syncs over to the ftp site herre: http://genome.wustl.edu/pub/software/gms/testdata/GMS1/setup/archive-files/
- Then update $APPS_DUMP_VERSION in the gms makefile to point to the new archive
- Then update the paths in Genome/Model/Tools/BioSamtools/ErrorRate.pm

**Comment by gatoravi** [comment]
ok, i can look into this. I also see this error, ERROR: Failed to run BamQc tool at /opt/gms/YBPD617/sw/genome/lib/perl/Genome/InstrumentData/AlignmentResult/Merged/BamQc.pm line 175. Is this just related to the bam-errorrate error ?

**Comment by malachig** [comment]
I believe this is related.  Just a different part of the stack of errors.

**Comment by gatoravi** [comment]
A couple of questions,
1. Who do I get in touch with regarding installing the tools at  /gsc/pkg/bio/bam-errorrate/, looks like these directories have systems group permissions on them and I don't think it might be as simple as copying the executable over.
2. Is this  directory unique to the standalone gms,? do we just archive a subset(or all) of these applications and stage them on the FTP site ? Is this archiving done manually ?

**Comment by malachig** [comment]
Apparently you have to log into the box 'deploy' to put stuff there.

The archive is updated manually and then staged manually.  Take a look at
the existing archive, where it is stored, and how it looks unpacked on the
stand alone gms once installed.

I'm away from my computer right now, but tomorrow we can work on this
together if you want.

**Comment by gatoravi** [comment]
yeah, I think it would be useful to go through this together !

**Comment by gatoravi** [comment]
this error appears to have been fixed by the steps mentioned above.
