### ISSUE TITLE
Failure to get disk usage for staging error

### ISSUE THREAD

**Issue by malachig** [genome/gms#43]
I suspect that this issue is specific to the clia1 test environment:

When running a reference-alignment build, I get the following error within a few minutes of the build starting

2013-11-22 17:34:27-0600 clia1: Use of uninitialized value in concatenation (.) or string at /opt/gms/4K8W670/sw/genome/lib/perl/Genome/SoftwareResult/Stageable.pm line 61.
2013-11-22 17:34:27-0600 clia1: ERROR: Failed to get disk usage for staging: 
2013-11-22 17:34:27-0600 clia1: Failed to get disk usage for staging:  at /opt/gms/4K8W670/sw/genome/lib/perl/Genome/SoftwareResult/Stageable.pm line 62.

The problem seems to be in:
Genome::Sys->disk_usage_for_path

This method lives in Genome/Sys.pm where the following command seems to be failing on execution:
my $cmd = "du -sk $path 2>&1";

There are a couple things going on here.  First, I suspect the error checking logic in this method is not quite catching the situation I have here.  But the main problem I suspect is that a permissions issue is preventing the build process from completing this 'du' command.

With the current user setup, files created by 'gmsuser' by default belong to the 'sudo' group.  Perhaps the problem is that the 'genome' user is not in that group?  Perhaps does not matter but files created during the build process are sometimes owned by the 'sudo' group and sometimes by the 'genome' group.
- Probably not related, but I noticed that temp did not have the sticky bit set so I did:
  sudo chmod 1777 /tmp
- Actually I think it might be this line in "Genome/SoftwareResult/Stageable.pm"
  61     unless ($usage = Genome::Sys->disk_usage_for_path($self->temp_staging_directory)) {
- Changing to this seems to have unblocked me
  61     unless (defined($usage = Genome::Sys->disk_usage_for_path($self->temp_staging_directory))) {

That line calls a method 'temp_staging_directory' that is implemented in Genome/Sys.pm 

At the time the directory was tested for size during the build process it contained two empty sub-directories.  Running 'du -sk' reports 0 as usage and the pathway queried.  This string is correctly parsed, makes it through the sanity checks in temp_staging_directory(), and returns as 0.  Where it errors out because of unless(0).

Isn't '0' a valid value for du?

**Comment by malachig** [comment]
The fix described above seems to be working.  

TODO: commit and push this fix to gms-core master branch, run test suite, then commit and push to gms-core pub branch.

**Comment by gatoravi** [comment]
I've updated the code in both the master and gms-pub, this can be seen here https://github.com/genome/gms-core/commit/d1c00d8e403f5a8fe9269befc03e19e5f302ef5c and here https://github.com/genome/gms-core/commit/0fdf11238643c5334b977e6f531b2e43d71e4a26

**Comment by malachig** [comment]
This issue has been resolved.  Disk usage seems to be reported correctly in the standalone GMS, tests passed after committing this change to gms-core master.  It now handles the unusual situation where certain filesystems report du of 0 when the contain only empty directories.
