### ISSUE TITLE
UR warnings when using --help with a genome command (from UR/ModuleBase.pm)

### ISSUE THREAD

**Issue by malachig** [genome/gms#45]
This warning is seen within the stand alone GMS, but not within TGI:

%  genome model list --help

Missing argument in sprintf at /opt/gms/4K8W670/sw/ur/lib/UR/ModuleBase.pm line 708.
Invalid conversion in sprintf: "%"" at /opt/gms/4K8W670/sw/ur/lib/UR/ModuleBase.pm line 708.

**Comment by gatoravi** [comment]
Is there a specific genome command that throws this warning ? I tried this with a couple of commands but don't seem to get this warning on the blade.

**Comment by gatoravi** [comment]
OK, I see it with `genome model list --help`

**Comment by gatoravi** [comment]
It looks like the problem was introduced in this commit https://github.com/genome/UR/commit/d4ddfbba9c4703b13e20346356ff4f142160463f but still can't figure this out.

**Comment by gatoravi** [comment]
this code has been changed in master and seems to be handling the sprintf arguments the right way, need to find the best way to incorporate those changes.

**Comment by malachig** [comment]
It looks like an update to our UR branch by merging in from master would help this issue.  I'm not sure how we have been handling this, but we have a 'gms-pub' branch of UR that is no out of date.  Furthermore, it seems that updates within TGI are not being pushed to github at all.  The last push to UR master branch occurred on October 9th (a394ba1ba82a108c326937632ec7714a47d21557).

**Comment by sakoht** [comment]
@malachig cc @obigriffith @gatoravi: your problems definitely go away with the latest internal UR.  Just need to get those pushed to github.

To run with a copy of the internal appserver version:

``` sh
export PERL5LIB=/home/ssmith/internalur:$PERL5LIB
genome taxon list --help
```

I emailed @nnutter, @kindjal, @amb43790, @jeldred, @jasonwalker80 so they can follow up here as well.

**Comment by sakoht** [comment]
To manually sync from your checkout, in case it takes a while to figure out how to keep github in sync:

``` sh
# get your checkout up-to-date
cd genome/ur
git fetch origin
git checkout master
git pull origin master

# add a remote for github and get it up-to-date with master
git remote add github git@github.com:genome/ur
git fetch github
git push github master

# sync gms-pub
git checkout github/gms-pub -b gms-pub
git merge master
### hope there are no conflicts, if you can't resolve something email me
git push github gms-pub

# get your checkouts back to the "right place" for internal dev
cd ..
git submodule update
```

**Comment by brummett** [comment]
Latest UR is now pushed to github.  We'll get automatic syncing working again shortly.

**Comment by malachig** [comment]
Comment from Nathan:

If you want to merge manually you can do:

cd $YOUR_UR_REPO
git remote add github git@github.com:genome/UR.git
git fetch --all
git push github origin/master:gms-pub

**Comment by malachig** [comment]
Nathan helped me merge UR master into UR gms-pub.  These warnings are now gone.

Right now the only difference between these two is the following code of slightly unknown origin/motivation in 11  lib/UR/Object/Type/InternalAPI.pm (from Scott?  or Avi?)

```
-my $uuid_generator;
 sub autogenerate_new_object_id_uuid {
-    my $uuid_generator ||= do {
-      require OSSP::uuid;
-      OSSP::uuid->new;
-    };
-    $uuid_generator->make("v1"); 
-    my $uuid = $uuid_generator->export("str"); 
-    $uuid =~ s/-//g; 
+    require Data::UUID;
+    my $uuid = Data::UUID->new->create_hex();
+    $uuid =~ s/^0x//;
     return $uuid;
 }
```

Can someone comment on the motivation for this change?  We would like to resolve this difference and avoid all forking of UR in the future...  If there is a genuine need for this we can try to reconcile it with master, if not we should just switch to using the version from UR master.

I will leave this issue open until we decide how to proceed with the harmonizing of UR master and UR gms-pub

**Comment by malachig** [comment]
According to Scott he was testing this new UUID library to see if it could create sortable UUIDs, but it didn't work as desired.  The new library is apparently not compatible with LIMS code used within the TGI.  But we should be able to revert to using the library currently in UR master.  We should do that since we don't really need to be different here...

To be clear.  Change the code above in the UR gms-pub branch to be identical to what is in the UR master branch.  Just strategically make that one change.  We will hold off on a full merge for a bit longer.

**Comment by gatoravi** [comment]
This change has been reverted in the gms-pub branch of UR. This change needs to be pushed to the internal UR repo which is being set up. 

Note: Henceforth we will be pulling using a tag in the master branch of UR instead of using the 'gms-pub' branch. 
This issue is effectively closed.

**Comment by sakoht** [comment]
You can just blow away the branch and make the tag "gms-pub" if you want.  The installer doesn't care if it's a branch or a tag when it does checkout.

**Comment by gatoravi** [comment]
True. We decided to keep the branch just in case we ever had to make a change unique to the gms(yes this is very unlikely :)).

**Comment by malachig** [comment]
This issue has been resolved.  The warnings are gone.  We are currently using a UR tag ('gms-pub-tag') instead of a branch for the UR repo within the sGMS.  The next time we do a complete merge of TGI code into sGMS we will create a new tag or point the current tag to a new commit.  

https://github.com/genome/UR/tree/gms-pub-tag

Closing this issue for now.
