### ISSUE TITLE
Warnings from Reallocator.pm when abandoning builds

### ISSUE THREAD

**Issue by malachig** [genome/gms#46]
Use of uninitialized value in subroutine entry at /opt/gms/GD0T679/sw/genome/lib/perl/Genome/Disk/Detail/Allocation/Reallocator.pm line 52.
Use of uninitialized value in numeric gt (>) at /opt/gms/GD0T679/sw/genome/lib/perl/Genome/Disk/Detail/Allocation/Reallocator.pm line 60.

**Comment by gatoravi** [comment]
small change in reallocator.pm from master branch (gms-core repo) needs to be incorporated in the gms-pub branch to fix this issue.
`unless($self->kilobytes_requested) {
      $self->kilobytes_requested(0);
 }`

**Comment by malachig** [comment]
This has been merged into gms-pub and seems to have resolved the issue. Closing for now.

https://github.com/genome/gms-core/commit/b26bf2b3e5205359b25b2458ba60baf89e21dfd7
