### ISSUE TITLE
How does software get installed in the standalone GMS?

### ISSUE THREAD

**Issue by malachig** [genome/gms#49]
This issue is purely for the sake of documentation:

Software is installed many ways depending on where it comes from and the form it is available in:

Software that is available publicly as packages:
- Some software is installed directly in the gms/Makefile using 'sudo apt-get install' commands.  Some of these are listed directly in the Makefile, while others are listed in 'gms/setup/packages.lst'.

Software that is used within TGI comes in one of three ways:
- An archive of pre-compiled binaries specified by '$APPS_DUMP_VERSION' is installed during the make process.  These apps are manually installed software from within the TGI (/gsc/pkg/bio/*) that have not been successfully converted to debian packages yet.  These are installed into $(GMS_HOME)/sw/apps which can be accessed by the environment variable $GENOME_SW set in /etc/genome.conf . If you need to modify the packages that are being installed this way, unpack the most recent archive add/remove packages, repackage it with a name containing the new date and move it to the staging directory.
- An archive of pre-compiled JAVA binaries specified by '$JAVA_DUMP_VERSION' is installed during the make process.  These apps are also manually installed software that have not been packaged yet.  They are installed into $(GMS_HOME)/sw/java which can be accessed by the environment variable $GENOME_SW_LEGACY_JAVA set in /etc/genome.conf
- An archive of debian packages created within TGI are installed globally.  This archive is specified in the gms Makefile as $APT_DUMP_VERSION.  The creation of this archive of packages happens within TGI and is controlled by the git repo 'genome-snapshot-deps'.  Refer to issue #47 for further details.  This repo sets up the dependencies for both Ubuntu lucid and precise.  From this git repo of dependencies, an apt repo of software is created.  The standalone GMS obtains a version of this apt repo by running /gms/setup/stage/Makefile.  During installation, the apt repo gets placed here: $(GMS_HOME)/sw/apt-mirror-min-ubuntu-12.04-DATE

The archives mentioned above get placed in the following directory within TGI and from there they are staged to an FTP server that serves them up:
/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/setup/archive-files
http://genome.wustl.edu/pub/software/gms/testdata/GMS1/setup/archive-files

**Comment by indraniel** [comment]
It may be good to have these notes on the [github wiki pages section of the gms project](https://github.com/genome/gms/wiki).

**Comment by malachig** [comment]
Good idea.  As we gather more info like this we can put stuff there that is too verbose and developer focused for the main installation/tutorial document currently represented by the main README.md

**Comment by gatoravi** [comment]
The test data for the standalone gms is put here from within the TGI, 

/gscmnt/sata102/info/ftp-staging/pub/software/gms/testdata/GMS1/fs/ 

This directory is the root directory for all disk allocations on the standalone GMS. Anything that is put here is automatically synced to the FTP server to be downloaded from the standalone gms.

**Comment by malachig** [comment]
The documentation content of this  issue has been moved to the wiki. Closing this issue.
