### ISSUE TITLE
Missing Novocraft. "novosam path of version: 2.05.13 is invalid"

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#51]
When somatic variation is run, the 'sv_breakdancer_1.3_ novo-realign v1' step fails,

According to Genome/Model/Tools/Novocraft.pm

Novocraft is expected to be found in '$ENV{GENOME_SW} . '/novocraft/' 

but this directory does not exist on the standalone.This directory might have to packaged onto the apps.

similar to issue #41

**Comment by malachig** [comment]
Looks like this would should be reasonable to resolve but note that this tool may also have similar licensing issues as issue #47

**Comment by gatoravi** [comment]
Novoalign was added to the apps directory, a new tar ball with the apps was created and staged to the FTP site.

**Comment by malachig** [comment]
We were able to get past this point in somatic-variation, everything seems fine.  Closing for now.
