### ISSUE TITLE
run the web server on a different port

### ISSUE THREAD

**Issue by sakoht** [genome/gms#6]

**Comment by malachig** [comment]
Scott, can you elaborate on this issue please?

**Comment by sakoht** [comment]
I the web server runs on port 80 it will conflict with any existing install. If we pick a different port we can "own" it.

Not really important.

**Comment by malachig** [comment]
At this point I don't think we can support the scenario where someone has a server doing various stuff and they want to install the sGMS onto that beside what they are currently doing.  If you are not prepared to dedicate hardware to the sGMS, as it stands now you will likely have serious problems with installation and configuration.
