### ISSUE TITLE
Environment variable error during installation (Environment variable GENOME_DS_GMSCHEMA_OWNER set to public but there were errors)

### ISSUE THREAD

**Issue by malachig** [genome/gms#60]
During a fresh install on a VM I am now consistently seeing errors that were not previously encountered to my knowledge...

Environment variable GENOME_DS_GMSCHEMA_OWNER set to public but there were errors using Genome::Env::GENOME_DS_GMSCHEMA_OWNER:

**Comment by malachig** [comment]
Something fundamental has likely changed recently to cause this failure.  I'm guessing that it is the use of a new version of UR.  Now a git tag instead of a git branch.  Avi recently switched the makefile to do this:

sudo git clone http://github.com/genome/UR.git -b gms-pub-tag $(GMS_HOME)/sw/ur

In the past we had a separate gms-pub branch for UR that we periodically updated by merging in changes from the master branch.  Now we are pulling a specific release. https://github.com/genome/UR/releases/tag/gms-pub-tag 

When this release was created, perhaps it included new changes that assume existence of the GENOME_DS_GMSCHEMA_OWNER variable?  This variable is defined in the gms-core code.  Since that code has evolved along with UR and we are out of sync within the sGMS, there may be a conflict.  I have confirmed that TGI now has Genome/Env/GENOME_DS_GMSCHEMA_OWNER.pm and sGMS currently does not.  There are many other environment variables that are missing here as well...

**Comment by malachig** [comment]
Actually, my first guess was wrong.  I think the 'GENOME_DS_GMSCHEMA_OWNER' error might have to do with this commit by 'guest' to gms that added some environment variables to gms/setup/etc/genome.conf (https://github.com/genome/gms/commit/e8f01ed84ddede63cb400416f26be94fca2659a0)

Apparently there should be symmetry between environment variables defined there and those defined in Genome/Env*.pm of gms-core.

**Comment by ernfrid** [comment]
I'd talk to Tony and Nathan and see if they know anything about either 
of these. I believe they've been adding additional configuration via 
environment variables to the main GMS and may know more about this.

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by malachig** [comment]
So Scott added these new environment variables to /etc/genome.conf in the gms commit mentioned above:

GENOME_DS_GMSCHEMA_AUTH.pm, GENOME_DS_GMSCHEMA_LOGIN.pm, GENOME_DS_GMSCHEMA_OWNER.pm, GENOME_DS_GMSCHEMA_SERVER.pm

Once these are defined, some low level checks start to fail.  To get things working I had to merge/copy the following in from gms-core master to gms-core gms-pub:

Genome/Env/GENOME_DS_GMSCHEMA_AUTH.pm
Genome/Env/GENOME_DS_GMSCHEMA_LOGIN.pm
Genome/Env/GENOME_DS_GMSCHEMA_OWNER.pm
Genome/Env/GENOME_DS_GMSCHEMA_SERVER.pm
Genome/Env/Required.pm (because the vars above are defined as Required)
Genome/Env.pm (new subroutine 'NAME' needed by Required.pm was added here)

**Comment by malachig** [comment]
I have pushed the fix described above to the gms-pub branch of gms-core here: https://github.com/genome/gms-core/commit/63d07d776db1d8ac41b24f2c977a7e235bc895f0

A completely fresh install in a VM was successful.  Closing this issue for now.
