### ISSUE TITLE
sup figure 1 B has commands not scrubbed of cruft like the box above it

### ISSUE THREAD

**Issue by sakoht** [genome/gms#7]

**Comment by malachig** [comment]
I'm guessing this has either been resolved or is a reference to the fact that sup figure 1B has a prompt that reads: '~/git/g6/lib/perl (master)> genome'.  

The other figures have grey borders and show the terminal window as well.  Maybe @sakoht could create an updated version that matches the style of the others a bit more closely.

**Comment by malachig** [comment]
@sakoht how did you produce the grey background for these images the supplementary figure 1B?  
The closest I could get was this:
![supfigureattempt](https://f.cloud.github.com/assets/856728/2232575/fda6b1a2-9b1d-11e3-93ba-45611be9a4f2.png)

**Comment by sakoht** [comment]
That's just a standard apple screenshot.  Is your gray different than mine?

**Comment by malachig** [comment]
The versions in the manuscript seem like they have a gradient to them...  Maybe just an optical illusion...  Anyway, the new version matches much better so I have swapped the old one with this one.  Closing this issue now.
