### ISSUE TITLE
webview issues

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#70]
In general the web views look and work awesome.

Minor issues:
1) links for stderr, stdout, data directory point to TGI urls - Just dropping the 'http://gscweb.gsc.wustl.edu' would work for now.
2) Subject links broken - I think they need to be 'localhost/sample/2889953341' instead of '/subject/2889953341'
3) GMS ID is blank. Either remove this from page headers or fix.

Feature requests:
1) A 'Builds' tab would be awesome.

![screenshot from 2014-01-16 22 32 55](https://f.cloud.github.com/assets/1638042/1937770/839066a0-7f30-11e3-88f1-dfdbc9dd90ba.png)

**Comment by acoffman** [comment]
I have created a JIRA issue for this and added it to the current sprint for our team.

**Comment by acoffman** [comment]
1.) All paths should start with '/' instead of a hardcoded domain now

2.) subject_path has been changed to sample_path on model and build views

3.) GMS_ID is now read from /etc/genome/sysid on application startup.

Working on a builds tab now.

**Comment by sakoht** [comment]
Sweet.

**Comment by sakoht** [comment]
If the links did not point to TGI, is the rails server prepared to serve up static files and directories?

I think we lean on /gscmnt having special meaning on the apache server.  Hopefully not a big change.

**Comment by obigriffith** [comment]
Did another mini-tour through the web viewer. The sample links and GMS ID are fixed. Thanks! The links to 'summary report' and 'data directory' still don't work though. It seems like they are just missing the leading slash. 

Additional minor issues observed:
1) There is TGI branding on the Summary/report.html pages. Should/can we remove this?
2) The link to summary reports has a spelling mistake in the path (sumamry).

Feature request:
1) As Scott says it would be ideal if certain static files and directories were served by apache. I think what we want is to serve "/opt/gms/GMS_ID/fs/GMS_ID/" where GMS_ID is read from /etc/genome/sysid or $GENOME_SYS_ID environment variable.

**Comment by acoffman** [comment]
There is now a builds tab that works - looking into the the new stuff mentioned now!

**Comment by sakoht** [comment]
> /opt/gms/GMS_ID/fs/GMS_ID/

It's an interesting question what disk should be served up, and I think what you have down there is the right answer by default.  You serve up data you create, but the data you import would not be.

Some future hypothetical version could get data from the source and/or from any other place that had downloaded it, ala BitTorrent.  Probably need a real permissions system before that...

So it won't expose:

> /opt/gms/THIS_GMS_ID/fs/OTHER_GMS_ID/

**Comment by obigriffith** [comment]
Builds tab looking good! Only issue I see still is that live filtering not working on it yet and not working 100% on some other tabs (filtering possible only on certain columns).

**Comment by acoffman** [comment]
- Summary Report and Data Directory links should now work
- Typo in Summary report path fixed
- The Summary/report.html pages aren't generated in this app - they must come from the pipeline somewhere, but they aren't in the rails app.
- The rails app won't serve up static files directly from arbitrary paths, that is something apache will need to do before requests hit the webviews.
- Looking into the filtering stuff Obi mentioned!

**Comment by obigriffith** [comment]
Tried to set up apache to serve arbitrary paths. If I create a second vhost I can serve up the arbitrary dir as desired (e.g., http://localhost/ directly serving /opt/gms/R80OA07/fs/R80OA07/info/) but then lose the app. From my very limited knowledge of apache it seems like just an Alias would be sufficient? I tried a whole bunch of variants along the lines of the following. I added only the Alias line and second <Directory></Directory>. The main web app still works but http://localhost/data/ gives me "The page you were looking for doesn't exist." Since that is a Ruby error I'm wondering if the webapp is ignoring/overruling my Alias?

```
<VirtualHost *:80>
  ServerName localhost
  ServerAlias some_hostname some_other_hostname
  DocumentRoot /var/www/gms-webviews/public
  Alias /data/ "/opt/gms/R80OA07/fs/R80OA07/info/"
  PassengerHighPerformance on
  <Directory /var/www/gms-webviews/public>
    AllowOverride all
    Options -MultiViews
  </Directory>
  <Directory "/opt/gms/R80OA07/fs/R80OA07/info/">
    Options +Indexes +FollowSymLinks +MultiViews
    AllowOverride none
    Order allow,deny
  Allow from all
  </Directory>

  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/json
  AddOutputFilterByType DEFLATE image/jpeg, image/png, image/gif
</VirtualHost>
```

**Comment by sakoht** [comment]
Is apache doing a reverse proxy to he rails server, or is the rails server being hit directly by the client ?

**Comment by acoffman** [comment]
The answer here (for someone doing something similar but with Django instead of Rails) seems to indicate that apache isn't tolerant of the trailing slash:

https://stackoverflow.com/questions/5682809/django-static-file-hosting-an-apache

**Comment by obigriffith** [comment]
Yeah. When I said I tried 'a whole bunch of variants' of the above I was referring to every combination of including or not including trailing slashes.

**Comment by acoffman** [comment]
Gotcha, I'll try and take a crack at it myself today or tomorrow then!

**Comment by acoffman** [comment]
Latest commit gets filtering and sorting working for all data table views. Looking at the apache stuff now.

**Comment by acoffman** [comment]
I don't have access to any of the standalone gms boxes afaik, but can one of you try the following apache config in place of the default one? It should mount /opt/gms at localhost/data

```
<VirtualHost *:80>
   ServerName localhost
   ServerAlias some_hostname some_other_hostname
   DocumentRoot /var/www/gms-webviews/public
   PassengerHighPerformance on
   Alias /data /opt/gms
   <Directory /opt/gms>
     Order deny,allow
     Allow from all
     SetHandler default-handler
   </Directory>
   <Directory /var/www/gms-webviews/public>
      AllowOverride all
      Options -MultiViews
   </Directory>
   AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/json
   AddOutputFilterByType DEFLATE image/jpeg, image/png, image/gif
</VirtualHost>
```

**Comment by acoffman** [comment]
@mkiwala-g pointed out that I can get on http://blade16-4-16/ myself and experiment. After a bit of finagling, I have a working apache config. It will mount /opt/gms at http://host/data/. You may need to update the environment variables for data_path accordingly. I have posted the working config below, and I will update the makefile to create this config instead of the current one.

Thanks!
Adam

```
<VirtualHost *:80>
   ServerName localhost
   ServerAlias some_hostname some_other_hostname
   DocumentRoot /opt/gms
   Alias /data /opt/gms
   <Directory /opt/gms>
     Order deny,allow
     Allow from all
     Options +Indexes +FollowSymLinks +MultiViews
   </Directory>
   <Location /data>
    PassengerEnabled off
   </Location>

   Alias / /var/www/gms-webviews/public
   <Location />
    PassengerBaseURI /
    PassengerAppRoot /var/www/gms-webviews
   </Location>
   <Directory /var/www/gms-webviews/public>
    Allow from all
    Options -MultiViews
  </Directory>


   AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml application/json
   AddOutputFilterByType DEFLATE image/jpeg, image/png, image/gif
</VirtualHost>
```

**Comment by obigriffith** [comment]
Excellent. Let me know when that has been pushed (and to which branch) 
and I will test it out on box at home.

**Comment by acoffman** [comment]
Its pushed up to github in a branch named "apache-conf"!

**Comment by obigriffith** [comment]
This seems to be working now. There are a few links still broken though:
ref build - fasta_file. Still appears as "http://opt/gms/GMS1/fs/ams1102/info/model_data/2869585698/build106942997/all_sequences.fa" without localhost prepended.

Need to check other builds more thoroughly once some have been run.

**Comment by acoffman** [comment]
Cool, I'll take a look at this

**Comment by acoffman** [comment]
This should be fixed in the latest push!.

**Comment by obigriffith** [comment]
It seems like the top level (workflow) error and stdout files on a build page are now being renamed to generic names like: workflow-server.err/out in the logs folder. The links would need to be reformatted to reflect that. Links to err/out files from individual workflow steps seem to be working though. 

Also, 'Summary Report' links under 'Last Complete Build' from most (all?) models except ref-aligns are broken. Probably because there is no summary report for those kinds of models? Maybe we should just drop those from the pages?

**Comment by acoffman** [comment]
Latest push will only show the summary report link on refalign builds!

I don't seem to be able to figure out what you mean with the workflow log links.. all the ones I'm trying seem to be working. Can you give me some example links or screenshots/paths?

Thanks!

**Comment by acoffman** [comment]
Obi came by and we took a look at this, it should be resolved in the latest push!

**Comment by obigriffith** [comment]
This all seems to be working as expected now.
