### ISSUE TITLE
Update from openlava branch release-2.0 to branch 2.2

### ISSUE THREAD

**Issue by malachig** [genome/gms#71]
There may be some improvements that have been committed to the openlava project that will help with some issues related to memory requests and reservation that we have been seeing in the sGMS.  

Currently we are installing by cloning a branch 'release-2.0' from github and build from that.  Perhaps it would have made sense to use the git tag '2.0a' instead?

In order to try branch '2.2' the following has to be done:
- Update the makefile in various places.  Specifically update the branch name in the make target 'done-host/git-checkouts'.  Then update version numbers in the make target 'done-host/openlava-install'.
- Update the path variable in: 'setup/etc/genome.conf'
- Update 'OPENLAVA_TOP' in 'setup/etc/init.d+openlava'
- It seems like config files are no longer put in place by the installer.  You will therefore need to add a line like the following to the Makefile:

``` bash
cd $(GMS_HOME)/sw/openlava/config; sudo cp lsb.hosts lsb.params lsb.users lsf.conf lsf.shared lsf.task openlava.sh openlava.csh /opt/openlava-2.2/etc/
```

To test, rebuild the system from scratch and make sure bjobs works and that interactions with openlava during builds are still working correctly.

**Comment by malachig** [comment]
The update from openlava release-2.0 to openlava 2.2 appears to be working.  It required changes to the Makefile, additional post install configuration compared to 2.0, and changes to other gms config files.  See this commit to gms (ubuntu-12.04 branch) for details:
https://github.com/genome/gms/commit/b0b79d95fd76f7392d58b1623dfaf14d4c9fd9ff  

Further testing where pipelines are actually run is desirable before closing this issue.

**Comment by sakoht** [comment]
Something that could have been a variable at the top too.

**Comment by malachig** [comment]
Further testing is going smoothly.  The first few builds have launched successfully and bjobs output is as expected.  After starting the openlava service and running some jobs, no serious issues are apparent in the log files here:

/opt/openlava-2.2/log/

**Comment by malachig** [comment]
Everything seems to be mostly fine with openlava 2.2.  The resource requirement statements returned by openlava 'bjobs -l' are different than they were in v2.0.  However, they continue to be vague, inaccurate, buggy, and in general largely useless for determining why some jobs will not start due to lack of resources (real or imagined by the scheduler)...  Some weirdness could be specific to a virtual machine environment.  Will have to confirm that.  We might consider reporting some of this behavior to the openlava project if we can make time for it.

In particular I am routinely encountering cases where a memory reservation by an rusage statement prevents a job from launching even if other jobs in the queue are not reserving memory, and sufficient physical memory is available according to the OS and lsload.  It almost seems that memory from previous requests is not being freed even after the job has completed.  More experimentation is required to determine if this behavior is consistent and if so how we can work around it.

Anyway, I don't think we are worse off than we were with 2.0.   We have obtained some new features, and documented the procedure for upgrading to future versions of openlava.

**Comment by malachig** [comment]
Considerable testing of openlava2.2 has been completed.  The problem described above relating to memory reservations seems to perhaps be particular to using openlava on a VM and has not been observed elsewhere.  Closing this issue.
