### ISSUE TITLE
Missing files/databases during annotate-and-upload-variants

### ISSUE THREAD

**Issue by malachig** [genome/gms#74]
Getting this error at the end of somatic variation runs:

```
2014-01-18 01:42:21+0000 precise6: Use of uninitialized value in join or string at /opt/gms/N5IQ908/sw/genome/lib/perl/Genome/Model/SomaticVariation/Command/AnnotateAndUploadVariants.pm line 284.
2014-01-18 01:42:23+0000 precise6: Getting annotation files for species human of version build37, dbsnp version 132
2014-01-18 01:42:23+0000 precise6: Command module died or returned undef.
2014-01-18 01:42:23+0000 precise6: Can't call method "data_directory" on an undefined value at /opt/gms/N5IQ908/sw/genome/lib/perl/Genome/Model/SomaticVariation/Command/AnnotateAndUploadVariants.pm line 
507.
```

I suspect we currently have no procedure for getting the databases referenced in the this module into the sGMS:

``` perl
   488 sub _get_human_sv_annot_file {
   489     my $self = shift;
   490     my $type = $self->_get_db_version();
   491     my $dbsnp_version;
   492     my $species = "human";
   493 
   494     if ($type eq "build36") {
   495         $dbsnp_version = "130";
   496     }
   497     elsif ($type eq "build37") {
   498         $dbsnp_version = "132";
   499     }
   500 
   501     return unless $type and $dbsnp_version;
   502     $self->status_message("Getting annotation files for species $species of version $type, dbsnp version $dbsnp_version");
   503     my $segdup = Genome::Db->get(source_name => 'ucsc', database_name => $species, external_version => $type);
   504     my $dbsnp = Genome::Db->get(source_name => 'genome-db-dbsnp', database_name => "$species/$type", external_version => $dbsnp_version);
   505     my $dbvar = Genome::Db->get(source_name => 'dbvar', database_name => $species, external_version => $type);
   506     return {
   507         segdup => $segdup->data_directory . '/segdup.tsv',
   508         dbsnp  => $dbsnp->data_directory . '/dbsnp.csv',
   509         dbvar  => $dbvar->data_directory . '/dbvar.tsv',
   510         };
   511 }

```

This issue is related to issue #56

**Comment by sakoht** [comment]
Those could be made inputs on the model.  Even if v1 doesn't pass them through and has a hard-coded internal value.  

Effectively the input has done its job by ensuring that the subsequent step won't crash, though it 'a far more elegant to actually pass the value through the code.

Easy short term fix: add "genome db install" to the Makefile for these explicitly for now.

**Comment by malachig** [comment]
My plan was the "genome db install" approach.  For consistency I was thinking of adding the actual installation of these to "genome model import metadata" where the others are already being installed.  So far, to run the demonstration analysis we install one version (github branch) of each of these:
- 'cosmic'  branch '61_v1' of https://github.com/genome-vendor/genome-db-cosmic-data
- 'tgi cancer-annotation' branch 'human-build37-20130401' of https://github.com/genome-vendor/genome-db-tgi-cancer-annotation-data
- 'tgi misc-annotation' branch 'human-build37-20130113' of https://github.com/genome-vendor/genome-db-tgi-misc-annotation-data

We will need to add and setup the following repos to github:
https://github.com/genome-vendor/genome-db-ucsc-data
https://github.com/genome-vendor/genome-db-dbsnp-data
https://github.com/genome-vendor/genome-db-dbvar-data

The data for these exists (and is editable from our 'deploy' server') here:
/gsc/scripts/opt/genome/db/ucsc/
/gsc/scripts/opt/genome/db/genome-db-dbsnp/
/gsc/scripts/opt/genome/db/dbvar/

**Comment by malachig** [comment]
Create branches as follows:
- ucsc
  - human-build36
  - human-build37
- dbsnp
  - human-build36-130
  - human-build37-132
- dbvar
  - human-build36
  - human-build37

**Comment by malachig** [comment]
These databases can now be installed using the same approach as that used for cosmic, tgi/misc-annotation, and tgi-cancer-annotation.  Example commands:

genome db ucsc install --species=human --branch=human-build37
genome db db-var install --species=human --branch=human-build37
genome db dbsnp install --species=human --branch=human-build37-132

These will be run automatically during 'genome model import metadata'.

These changes were added to gms-core repo (both master and gms-pub branches):
https://github.com/genome/gms-core/commit/7c34919ef99bf93a6da4edf728482212296baa64
https://github.com/genome/gms-core/commit/26b4d6ee69fb070a8ab250ef6465ca92ec59e32d

**Comment by malachig** [comment]
This seems to be working now.  Still need to test that the right thing happens with a clean install.  Once that is done, this issue can be closed.

**Comment by malachig** [comment]
Some logic introduced above to deal with the dbsnp database is now messing up proper installation of tgi databases:

Need to get all 6 of these work properly
- genome db cosmic install --branch=61_v1
- genome db tgi install --subsource=cancer-annotation --species=human --branch=human-build37-20130401
- genome db tgi install --subsource=misc-annotation --species=human --branch=human-build37-20130113
- genome db ucsc install --species=human --branch=human-build37
- genome db db-var install --species=human --branch=human-build37
- genome db dbsnp install --species=human --branch=human-build37-132

Another minor fix was pushed to gms-core (both master and gms-pub) here:
https://github.com/genome/gms-core/commit/13ee0a34d111cd5b83f0b08053a19eb10e9e5075
https://github.com/genome/gms-core/commit/34efabab2c004278c755ada6b453f2c8d47ac61d

**Comment by malachig** [comment]
Haven't noticed any problems with this.  But since these databases are used to annotate SVs and it appears that there is a problem with SV results (issue #91) we should leave this issue open for now.

**Comment by malachig** [comment]
Another database was found to be missing and needed for annotation of SVs.  'cancer-gene-list' has been added to github, modules created for importing it, and the import step added automatically to genome model import metadata.  The following seven file based databases are now installed in the sGMS:

```
genome db cosmic install --branch=61_v1
genome db tgi install --subsource=cancer-annotation --species=human --branch=human-build37-20130401
genome db tgi install --subsource=misc-annotation --species=human --branch=human-build37-20130113
genome db ucsc install --species=human --branch=human-build37
genome db db-var install --species=human --branch=human-build37
genome db dbsnp install --species=human --branch=human-build37-132
genome db cancer-gene-list install --species=human --branch=human-1
```

**Comment by malachig** [comment]
This latest round of fixes were committed to gms-core:

master branch:
https://github.com/genome/gms-core/commit/8685bdd433a02771b6962fe5987cdeb6a1428858
https://github.com/genome/gms-core/commit/dde1f5fea559d20cbc39a8c2a31e8ee9f1a47b7a

gms-pub branch:
https://github.com/genome/gms-core/commit/415e231b9818087704872405b7db84b50caedbb3
https://github.com/genome/gms-core/commit/c9b4f14f9e2ad4bb89fa2a106f9e2b9f91cf9891

**Comment by malachig** [comment]
This appears to all be working now but we are waiting for some test runs to complete to confirm that all SV results are created, properly merged, annotated and summarized in the clin-seq output.

**Comment by malachig** [comment]
This issue is now resolved.  clin-seq builds now contain the expected SV summaries, plots, etc.
