### ISSUE TITLE
how to re-image blade-16-4-16

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#78]
to re-image:

wget -q -O - "http://puppet.gsc.wustl.edu:3001/image=10.6.0.73"

to turn off that image flag, say if you changed your mind:

wget -q -O - "http://puppet.gsc.wustl.edu:3001/default=10.6.0.73"

then do,

 'sudo reboot'

**Comment by malachig** [comment]
We are still using blade16-4-16 as one of our test environments.  Leaving this open for now.

**Comment by malachig** [comment]
We are currently not testing on this blade.  Testing is continuing on clia1, Amazon AWS, Mac desktops, consumer hardware, etc.  Closing this issue for now.
