### ISSUE TITLE
Error running wget during SummarizeBuilds step of clin-seq

### ISSUE THREAD

**Issue by malachig** [genome/gms#88]
Getting the following error:

```
RUN: wget --no-check-certificate -O /dev/null "/genome/model/build/set/coverage.html?&id=0e50e40098684444b95fb1c0579b12e8&id=9c1833739c8740528f376feb18797c51" 1>/dev/null 2>/dev/null
Command module died or returned undef.
ERROR RUNNING COMMAND.  Exit code 1 from: wget --no-check-certificate -O /dev/null "/genome/model/build/set/coverage.html?&id=0e50e40098684444b95fb1c0579b12e8&id=9c1833739c8740528f376feb18797c51" 1>/dev/null 2>/dev/null
```

Related to this code:

``` perl
    495     if ($id_string =~ /\d+/){
    496       my $cov_report_url = Genome::Utility::List::join_with_single_slash($ENV{GENOME_SYS_SERVICES_WEB_VIEW_URL}, "/genome/model/build/set/coverage.html?"."$id_string");
    497       $self->status_message("\nView here:\n$cov_report_url");
    498       #Use wget to retrieve the page so that is is cached and ready to go...
    499       my $wget_cmd = "wget --no-check-certificate -O /dev/null \"$cov_report_url\" 1>/dev/null 2>/dev/null";
    500       $self->status_message("\n");
    501       Genome::Sys->shellcmd(cmd => $wget_cmd);
    502     }

```

**Comment by malachig** [comment]
Many things in this step of the clin-seq workflow will fail because the LIMS tool illumina_info or database it queries are not available outside TGI.  Most of these steps will tolerate failure.

The above failing step will also fail unless the web view service is properly configured and $ENV{GENOME_SYS_SERVICES_WEB_VIEW_URL} is properly defined.

This part I have updated in gms with this commit:
https://github.com/genome/gms/commit/6a0a9d699368b5a0b579c8346a000fa5a98683ba

We could add fault tolerance to that step, but should also make sure the web-service is working and that the reference coverage report can be viewed...

**Comment by sakoht** [comment]
Is this something we should disable and save for a next iteration?

The web interfaces packaged to go with the GMS are entirely new, and it may take a long time for old reports to migrate this report.  We don't discuss it in the paper, so maybe we can push this off?

**Comment by malachig** [comment]
For now I have changed this to tolerate failure of this wget call.

**Comment by malachig** [comment]
The SummarizeBuilds step of clin-seq is now succeeding.  All of the LIMS reports from 'illumina_info' are missing and the link to the coverage report is not being automatically cached.  The coverage report itself may not be working either...  If true this would be unfortunate because we are showing one of these report right in Figure 2 of the manuscript...

**Comment by malachig** [comment]
Within TGI, we can get a nice reference-alignment coverage report in the webviews.  For example, https://imp-apipe.gsc.wustl.edu/view/genome/model-group/coverage.html?id=10318a594cd54dd39fe04d5e1217dd19

Is that correct?

In the sGMS we don't use these webviews and have instead elected to use the newer, faster ruby based gms-webviews.  Does this new webview re-implement this report? If not, is there a plan to do this?  

@acoffman can you comment on this?

**Comment by acoffman** [comment]
Unfortunately, the new web views do not have a coverage report view and AFAIK, there isn't a plan to implement one.

**Comment by sakoht** [comment]
Do you know if the plan is to keep the old web service, or to stop having
the report?

On Monday, February 24, 2014, Adam Coffman notifications@github.com wrote:

> Unfortunately, the new web views do not have a coverage report view and
> AFAIK, there isn't a plan to implement one.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/genome/gms/issues/88#issuecomment-35917766
> .

## 

Sent from Gmail Mobile

**Comment by malachig** [comment]
For now I am closing this issue.  We should still come up with some method for producing coverage reports in the sGMS though...
