### ISSUE TITLE
Mutation-spectrum step fails on an R error

### ISSUE THREAD

**Issue by malachig** [genome/gms#89]
Seeing the following error during these steps:
Creating mutation spectrum results for wgs snvs using create-mutation-spectrum
Creating mutation spectrum results for exome snvs using create-mutation-spectrum

```
Problem running the R command:
plot_mutation_spectrum_seq_contextV2(input4type="/opt/gms/PEL8970/fs/PEL8970/info/model_data/18177dd5eca44514a47f367d9804e17a/build0330648363024e378eeeca66afc9ef55/TST1/mutation-spectrum/exome/mutation_spectrum_sequence_context/TST1.data.tsv.4type",input2type="/opt/gms/PEL8970/fs/PEL8970/info/model_data/18177dd5eca44514a47f367d9804e17a/build0330648363024e378eeeca66afc9ef55/TST1/mutation-spectrum/exome/mutation_spectrum_sequence_context/TST1.data.tsv.2type",output_file="/opt/gms/PEL8970/fs/PEL8970/info/model_data/18177dd5eca44514a47f367d9804e17a/build0330648363024e378eeeca66afc9ef55/TST1/mutation-spectrum/exome/mutation_spectrum_sequence_context/TST1.mutation-spectrum-sequence-context.pdf",plot_title="Mutation Spectrum Sequence Context for TST1") 
Got the error:
argument "values" is missing, with no default
```

Its possible that the error is related to a typo in this module:
Genome/Model/Tools/R/CallR.pm.MutationSpectrum.R 

In this module various calls are made to ggplot2 'scale_fill_manual()'.  This function expects an argument 'values'.  But in some places, 'value' is being used instead.

**Comment by malachig** [comment]
The above fix, did resolve this error.  But another appeared.  It looks like these errors are due to the version of ggplot2 that we have installed in the sGMS versus within TGI (where in both cases we are using R 2.15.2).

Within TGI we are using:  ggplot2_0.8.9 
Within the sGMS we use: ggplot2_0.9.3.1

genome-snapshot-deps-r specifies ggplot2 like so:
r-cran-ggplot2 (>= 0.8.9-1cran1)
r-cran-ggplot2 (>= 0.8.9-1cran1)

Depending on what happens with our R packaging issue ( #59 ), this problem may go away if we wind up installing a specific version of ggplot2...

In the custom R installation we are doing we could try something like this:

```
packageurl <- "http://cran.r-project.org/src/contrib/Archive/ggplot2/ggplot2_0.8.9.tar.gz"
install.packages(packageurl, contriburl=NULL, type="source")
```

**Comment by sakoht** [comment]
If we swap >= for =, it will try to pin on the older version.  The question is just whether the older pkg has any issues with other Ubuntu 12.04 dependencies.

**Comment by malachig** [comment]
It is unlikely to be that simple.  The R packages in Ubuntu are a nightmare.  We have been working for weeks to get a working version of R installed in Ubuntu from packages.  The version that was being installed, did not prevent make from completing but it had about 10 problems with it and many packages were not loadable.  Many R capabilities were not functional, etc.  Several Ubuntu packages had to be added and we are closer to having a working setup.  The last time we tried to swap some ">=" for "=" in genome-snap-deps-r we created a completely broken APT repo that was unusable.  Matt is actively working on this issue and it sounds like he is close to a working solution.  

For now, the custom R installation method I adopted gets us very close to have R installed the way we need.  Except that it installs a working version of ggplot2 that is slightly too new.   ggplot2 had a major interface overhaul in the transition from 0.8.9 to 0.9.X.  We need the old version unfortunately.  In addition to Matt's efforts, I'm looking into updating the manual solution for this right now.

**Comment by malachig** [comment]
The install.packages method described above did not work because the R package management system does not allow installation of versions that are not officially supported (including versions that used to be installed successfully for a particular base R).  Instead I have modified the custom R installation to manually install the correct version of ggplot2 (0.8.9) from packages downloaded directly as tar.gz files.  

To get this to work I also had to install the 8 R package dependencies of ggplot2.  For all 8 of these, I selected the version currently used within TGI.  Since these are being installed manually, they must be installed in the correct order.

I also had to modify the Bioconductor installation to not perform package upgrades.  Otherwise it simply overrides the specific versions installed manually.

All of this was committed here:
https://github.com/genome/gms/commit/ad37f0bf7e45de689bb8c3ef91e704aec7312155

To test that the correct version of ggplot is installed do the following:

``` R
library("ggplot2")
sessionInfo()
```

**Comment by malachig** [comment]
This is still not working because although the correct version of ggplot2 is now being installed, something else is overriding the manual installation of the 'plyr' library.  I am manually installing 'plyr_1.4' but 'plyr_1.8' is ultimately installed anyway.  'plyr_1.8' has a known compatibility issue with 'ggplot2_0.8.9'.  

It looks like plyr is being upgraded when CummeRbund gets installed despite my use of 'suppressUpdates=TRUE' in biocLite.  This suppression of updates appears to be working for all other pre-installed packages...

Attempting to override again back to plyr 1.4 after Bioconductor finishes...  See this commit for details
https://github.com/genome/gms/commit/da10a518db0ec51caca4ac6c22df2b1b38373eb6

**Comment by malachig** [comment]
Looks like this last fix worked.  Mutation spectrum steps in the clin-seq workflow are succeeding now.  We should test that R still get installed correctly in a fresh install (no reason that it shouldn't) and then close this issue.

**Comment by sakoht** [comment]
It's too bad R doesn't let you install old versions.

And too bad the Debian packaging wasn't working, as it is supposed to help you stay in the past when you want.

Glad it's working in any case.  I took a snapshot of `dpkg -l` from Obi's box so we can get back to that if we find later upgrades cause problems.  I'll commit it to the repo.

**Comment by malachig** [comment]
Related to this issue ... since it was CummeRbund that seemed to be insisting on a newer version of the plyr library and ggplot2 (0.8.9) that is insisting on an older version we should confirm that CummeRbund is actually working in the standalone environment.  These results go into the differential-expression build dir.

**Comment by malachig** [comment]
CummeRbund does appear to be working.  The manual R installation we are doing is far from optimal but it does appear to be working.  The latest developments on this installation methods are described in issue #100.  

We can close this issue as soon as we have a new successful mutation-spectrum result from the latest round of tests.

**Comment by malachig** [comment]
I think I may have spoken too soon.  CummeRbund did work on the last test on clia1, but now it is not working.  The problem may have been introduced when many R cran packages were pegged to specific versions of packages to match those used within TGI.  Furthermore, it seems that there are problems with CummeRbund within TGI as well.  I am using the following workflow to test:
http://www.bioconductor.org/packages/release/bioc/vignettes/cummeRbund/inst/doc/cummeRbund-example-workflow.R

I am getting this error from CummeRbund in the sGMS:

``` R
> d<-dispersionPlot(genes(cuff))
Error in rename(x, .base_to_ggplot, warn_missing = FALSE) : 
  could not find function "revalue"
```

Within TGI I get this error:

``` R
> d<-dispersionPlot(genes(cuff))
Error in function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘rename’ for signature ‘"uneval"’
```

In both places plyr_1.4 is installed.  If I update to plyr_1.8 the workflow works.  Using an earlier version of CummeRbund might be another option.  The versions of CummeRbund and Cuffdiff have to be matched to some degree.

Note that plyr is used by ggplot2.  The attempted update of plyr by CummeRbund was apparently for good reason.  However, if we bump to plyr_1.8 it is possible that we will introduce problems in tools that use ggplot2.  For example, mutation-spectrum.  

Testing now to see if both the CummeRbund command of the differential-expression pipeline and the all plotted results of clin-seq (including mutation-spectrum) still work with plyr_1.8.

**Comment by malachig** [comment]
Confirmed.  With plyr_1.8, mutation spectrum fails and cummeRbund succeeds.  With plyr_1.4, mutation-spectrum succeeds and cummeRbund fails.  Maybe 1.5, 1.6, or 1.7 will work for both...  Or perhaps an older version of cummeRbund (assuming that it is compatible with the cuffdiff results).  Or perhaps mutation-spectrum should be updated to work with the updated version of plyr.  Perhaps @clu has already done that.

**Comment by sakoht** [comment]
If either mutation spectrum or cummeRbund is given a private install of
pylr does it get let pylr effectively upgrade separately?

Some adjacent directory to one of the tools gets the alt version and the
wrapping script tweaks the environment so it will come first.  The default
install could be the one that woks with most other libs (ggplot2?)

On Sunday, February 23, 2014, Malachi Griffith notifications@github.com
wrote:

> Confirmed. With plyr_1.8, mutation spectrum fails and cummeRbund succeeds.
> With plyr_1.4, mutation-spectrum succeeds and cummeRbund fails. Maybe 1.5,
> 1.6, or 1.7 will work for both... Or perhaps an older version of cummeRbund
> (assuming that it is compatible with the cuffdiff results). Or perhaps
> mutation-spectrum should be updated to work with the updated version of
> plyr. Perhaps @clu https://github.com/clu has already done that.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/genome/gms/issues/89#issuecomment-35860977
> .

## 

Sent from Gmail Mobile

**Comment by malachig** [comment]
To test the mutation-spectrum code:

```
plot_mutation_spectrum_seq_contextV2(input4type="/opt/gms/KE56B14/fs/KE56B14/info/model_data/18177dd5eca44514a47f367d9804e17a/buildeddf0b17acd54f6abd42bd6840edea85/TST1/mutation-spectrum/wgs/mutation_spectrum_sequence_context/TST1.data.tsv.4type",input2type="/opt/gms/KE56B14/fs/KE56B14/info/model_data/18177dd5eca44514a47f367d9804e17a/buildeddf0b17acd54f6abd42bd6840edea85/TST1/mutation-spectrum/wgs/mutation_spectrum_sequence_context/TST1.data.tsv.2type",output_file="/opt/gms/KE56B14/fs/KE56B14/info/model_data/18177dd5eca44514a47f367d9804e17a/buildeddf0b17acd54f6abd42bd6840edea85/TST1/mutation-spectrum/wgs/mutation_spectrum_sequence_context/TST1.mutation-spectrum-sequence-context.pdf",plot_title="Mutation Spectrum Sequence Context for TST1")
```

To test the cummeRbund code:

```
# cp -r /opt/gms/KE56B14/sw/apps/R/R-2.15.2/lib/R/library/cummeRbund/extdata /tmp
test_dir = '/tmp/extdata'
library(cummeRbund)
cuff <- readCufflinks(dir=test_dir)
cuff
d<-dispersionPlot(genes(cuff))
d
```

Notes:
- Updating plyr from version 1.4 to version 1.5, 1.6, or 1.7 does not help
- Updating ggplot2 to version 2_0.9.2.1 (or greater most likely) allows the cummeRbund code in differential expression to succeed.  Doing so adds two more R libraries dependencies: 'memoise' (memoise_0.1.tar.gz) and 'gtable' (gtable_0.1.2.tar.gz).  Of course with this version, mutation-spectrum no longer works.

**Comment by malachig** [comment]
I eventually got both cummeRbund and mutation-spectrum working by updating ggplot2 and modifying the mutation-spectrum code.  Mutation-spectrum now contains conditional logic to check the ggplot2 version.  If ggplot2 <= 0.8.9, the old syntax is used.  If ggplot2 >= 0.9.X, the new syntax is used.  

Note:
I only changed the functions that are actually used in the pipelines.  Further updating might be needed for users running additional methods of this tool at the command line.  Also, there may be other places in the pipelines that use ggplot2 that will need to be similarly updated.  This issue should not be closed until a new test run is successful from the beginning.  Relevant commits:

gms-core master
https://github.com/genome/gms-core/commit/2b665a104ad4367586cd43811d7dd33e270ae198

gms-core gms-pub
https://github.com/genome/gms-core/commit/51ea4a10227185f1553109f1fdcfc500695caa10

gms
https://github.com/genome/gms/commit/21fc3a5b1aa3dcfae3239fbea91f03585d295930
https://github.com/genome/gms/commit/8c110922e5d8adf36386bb94d4b7724ce73316b6
https://github.com/genome/gms/commit/db5415ae477761596699630824c7b9480e098ba3
https://github.com/genome/gms/commit/2bea8cdae5c88b0b758dc7a91053c490f26b973e
https://github.com/genome/gms/commit/3a78355f7cdc00d5534cde7fae124fabda018792

**Comment by malachig** [comment]
Both mutation-spectrum and cummeRbund results from R appear to be working cleanly now. Closing this issue.
