### ISSUE TITLE
Document sGMS on Github Wikis.

### ISSUE THREAD

**Issue by gatoravi** [genome/gms#95]
update the wiki to include information on install, working, example usage and debugging of the sGMS. Put all relevant information in one place for users and developers.
An example layout would look like this(from @obigriffith ), 
![photo](https://f.cloud.github.com/assets/764948/2078640/8f171796-8dc0-11e3-9b10-2a1c8a06c569.jpg)

The GitHub wiki pages are stored as git repos. To clone a wiki page go to the wiki and click on 'Clone URL', you can then clone the wiki repo with 'git clone'. For the gms repo this would look like `git clone git@github.com:genome/gms.wiki.git`

**Comment by malachig** [comment]
This documentation exercise is well underway on the github wiki:
https://github.com/genome/gms/wiki

There is plenty of work to be done there but I am closing the issue related to getting it started.
