### ISSUE TITLE
How are apt repos configured in the standalone GMS?

### ISSUE THREAD

**Issue by malachig** [genome/gms#98]
It is not clear what is going on with APT repo configuration in the standalone GMS.

The makefile includes various places that seem to be relevant.  For example,

``` make
   394 done-host/apt-config: done-host/puppet done-repo/unzip-sw-apt-mirror-min-ubuntu-12.04-$(APT_DUMP_VERSION).tgz
   395     #
   396     # $@:
   397     # done-host/apt-config:
   398     # configure apt to use the GMS repository
   399     #
   400     sudo -v
   401     sudo dpkg --force-confdef --force-confnew -i $(GMS_HOME)/sw/apt-mirror-min-ubuntu-12.04-$(APT_DUMP_VERSION)/mirror/repo.gsc.wustl.edu/ubuntu/pool/main/g/genome-apt-confi§
   402     sudo /bin/cp setup/debconf.in /tmp
   403     # findreplace WHATEVER /tmp/debconf.in
   404     sudo debconf-set-selections < /tmp/debconf.in
   405     touch $@    

```

This installs a debian package that contains 4 .list files (genome.list, puppet.list, r-bioconductor.list, r-cran.list).  It appears that these .list files wind up in /etc/apt/sources.list.d/*.  

It is not clear _how_ this happens though.  And the contents of these files are not valid for bioconductor.list or puppet.list.  Does this package install literally just place some files in /etc/apt/sources.list.d/ ?  Or is other configuration happening as well?

Later in the make process, this is done:

``` make
   407 done-host/etc: done-host/apt-config
   408     #
   409     # $@:
   410     # copy all data from setup/etc into /etc
   411     # 
   412     sudo -v
   413     [ -d /etc/facter/facts.d ] || sudo mkdir -p /etc/facter/facts.d 
   414     /bin/ls setup/etc/ | perl -ne 'chomp; $$o = $$_; s|\+|/|g; $$c = "sudo cp setup/etc/$$o /etc/$$_\n"; print STDERR $$c; print STDOUT $$c' | sudo bash
   415     sudo setup/bin/findreplace REPLACE_GENOME_HOME $(GMS_HOME) /etc/genome.conf /etc/apt/sources.list.d/genome.list
   416     sudo setup/bin/findreplace REPLACE_GENOME_SYS_ID $(GMS_ID) /etc/genome.conf /etc/apt/sources.list.d/genome.list
   417     sudo setup/bin/findreplace REPLACE_GENOME_HOST $(HOSTNAME) /etc/genome.conf
   418     sudo setup/bin/findreplace REPLACE_APT_DUMP_VERSION $(APT_DUMP_VERSION) /etc/apt/sources.list.d/genome.list
   419     sudo bash -c 'echo "/opt/gms/$(GMS_ID) *(ro,anonuid=2001,anongid=2001)" >> /etc/exports'    
   420     sudo chmod +x /etc/facter/facts.d/genome.sh
   421     touch $@

```

This appears to also produce an /etc/apt.sources.list.d/genome.list using this file as a template: https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/apt%2Bsources.list.d%2Bgenome.list.  The one that is actually used?

**Comment by malachig** [comment]
I tried dropping the 'done-host/apt-config' target.  A genome.list file still appears as expected and the other three do not.  The make fails on R dependencies.  Even if I create the correct r-cran.list file it still fails.

If I manually install 'genome-apt-config_1.0.0-2~Ubuntu~precise_all.deb' the make is able to succeed again.  

Bottom line, this package and the 'done-host/apt-config' are doing more than simply copying those .list files over.

**Comment by malachig** [comment]
One thing that was missing in my test above was GPG keys.  These are also installed by the 'genome-apt-config' package.  So if we want to drop use of that package we will need to handle the keys somehow.  Since we are only actually using the TGI package and r-cran the following might suffice:

r-cran:

``` bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
```

repo.gsc.wustl.edu (to use the TGI server OR an APT dump created from it)

``` bash
wget http://repo.gsc.wustl.edu/ubuntu/files/genome-institute.asc
sudo apt-key add genome-institute.asc
```

**Comment by malachig** [comment]
Another side note related to tidying up configuration of apt.  This code:

``` make
   402     sudo /bin/cp setup/debconf.in /tmp
   403     # findreplace WHATEVER /tmp/debconf.in
   404     sudo debconf-set-selections < /tmp/debconf.in
```

It looks like this code is half-baked and possibly unnecessary anyway?  A file with some debian package configurations is copied from gms/setup/debconf.in to /tmp.  A findreplace on this file is commented out and therefore does not happen.  The configuration options (which may or may not be correct without the findreplace) are then injected into the debconf database using debconf-set-selections.

These configuration values relate to a package 'nullmailer', a message transfer agent (MTA).  This package is never installed though...  Unless someone has an explanation for what was planned here, I'm tempted to remove this code.  We Perhaps configuration of this MTA was planned but never completed?  From the debconf-set-selections manual:

```
       Only use this command to seed debconf values for packages that will be
       or are installed. Otherwise you can end up with values in the database
       for uninstalled packages that will not go away, or with worse problems
       involving shared values.
```

On a related note, @gatoravi has been going down the road of using exim as the sGMS MTA.

**Comment by malachig** [comment]
Still have not been able to reproduce what genome-apt-config does.  I tried adding the following lines to the Makefile, commenting out the installation of genome-apt-config and adding this r-cran.list file here (https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/apt%2Bsources.list.d%2Br-cran.list):  

``` make
   417     # Add r-cran source and GPG keys for r-cran and TGI
   418     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
   419     wget http://repo.gsc.wustl.edu/ubuntu/files/genome-institute.asc
   420     sudo apt-key add genome-institute.asc
   421     # Remove multi-architecture package support (e.g i386)
   422     sudo mv /etc/dpkg/dpkg.cfg.d/multiarch /etc/dpkg/dpkg.cfg.d/multiarch.backup
```

Still did not work.  Many packages complain of having unresolved dependencies.

**Comment by malachig** [comment]
I now have two VMs sitting beside each other on my Mac.  Both were fresh installs of sGMS.  One uses the current default install by simply cloning gms from github.  The other drops installation of the genome-apt-config package described above and tries to reproduce configuration of the local TGI apt package and public r-cran apt repo.  This fails.  

It looks like perhaps, 'genome-apt-config' creates a file: '/etc/apt/preferences' with priority settings for various repos.  This has seven entries in it (see below).  Not sure how many of these are needed/valid...

```
Explanation: provides our packages at top priority
Package: *
Pin: release n=precise-genome-development
Pin-Priority: 1002

Explanation: The Genome Center's lucid repo contains some packages we need, but don't prefer this repo
Package: *
Pin: release n=lucid-genome-development
Pin-Priority: 900

Explanation: set precise default to 990, same as -t precise
Package: *
Pin: release n=precise
Pin-Priority: 990

Explanation: provides R at prio matching precise
Package: *
Pin: release o=CRAN
Pin-Priority: 990

Explanation: provides R at prio lower than CRAN or either genome center repo
Package: *
Pin: origin bioinformatics.rri.sari.ac.uk
Pin-Priority: 890

Explanation: provides an X lib for consed to work
Package: *
Pin: release o=LP-PPA-crcarlin
Pin-Priority: 300

Explanation: available only with apt-get -t natty
Package: *
Pin: release n=natty
Pin-Priority: -500
```

**Comment by malachig** [comment]
This issue is related to issues #59, #63, and #89

**Comment by sakoht** [comment]
@malachig did any feedback come from @kindjal or @nnutter on how this package works?

The overall idea is that the package is what someone who installs packages from gmt.genome.wustl.edu installs the genome-apt-config package first, and this prepares them to debian packaged software from apt.genome.wustl.edu.

The standalone GMS wants the same  sort of configuration, but needs to override a few things.  The big one being that, rather than using the public apt.genome.wustl.edu to get packages, it pulls from a file-based mirror.  So the GMS Makefile constructs a special genome.list, and stomps on the file created by the genome-apt-config.  This ensures that random changes over time to apt.genome.wustl.edu do not lead to different installs of the GMS.

If the *.list files are out of date, they should be updated, and the `genome-apt-config` package shoud be rebuilt.  Looking at the /etc/apt/ on any workstation or blade will be a good clue.  @kindjal knows what is being used day-to-day to ensure R package work on the TGI cluster, as puppet is probably being used to put those files out.

If the `genome-apt-config` package is dropped, whatever is in the puppet manifest that keeps those files up-to-date on blades could be used.

**Comment by malachig** [comment]
I have now dropped use of `genome-apt-config`.  All configuration is now specified in the make target `done-host/etc` and these files:  
https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/apt%2Bpreferences
https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/apt%2Bsources.list.d%2Bgenome.list
https://github.com/genome/gms/blob/ubuntu-12.04/setup/etc/apt%2Bsources.list.d%2Br-cran.list

Defunct repositories are no longer added.  Once we have a working set of packages for ubuntu precise that are all publicly available on our apt server this method could be replaced with configuration by puppet manifest.

Relevant commits:
https://github.com/genome/gms/commit/edde21a2685ac663b59f25b050fc4af646fafcc1
https://github.com/genome/gms/commit/d26b7fadcc7dd2a565f9d8c09e3a094482816d5e
https://github.com/genome/gms/commit/268c87ec003e30945438a737333179b7d4446102
https://github.com/genome/gms/commit/47ceef6d2f4f9180f3ea185bb7714f7be272f53b

**Comment by sakoht** [comment]
Nice.

**Comment by malachig** [comment]
This all seems to be working.  Refer back to this ticket for details on how apt-config is currently handled in the sGMS.  If a problem arises, this issue can be reopened.  Closing for now.
